# AutoGenerated File
# TODO: Add VulkanNim Header here
import std/sets

## Value Enums
type VkImageLayout * = enum
  ImageLayoutUndefined = 0  ## Implicit layout an image is when its contents are undefined due to various reasons (e.g. right after creation)
  ImageLayoutGeneral = 1  ## General layout when image can be used for any kind of access
  ImageLayoutColorAttachmentOptimal = 2  ## Optimal layout when image is only used for color attachment read/write
  ImageLayoutDepthStencilAttachmentOptimal = 3  ## Optimal layout when image is only used for depth/stencil attachment read/write
  ImageLayoutDepthStencilReadOnlyOptimal = 4  ## Optimal layout when image is used for read only depth/stencil attachment and shader access
  ImageLayoutShaderReadOnlyOptimal = 5  ## Optimal layout when image is used for read only shader access
  ImageLayoutTransferSrcOptimal = 6  ## Optimal layout when image is used only as source of transfer operations
  ImageLayoutTransferDstOptimal = 7  ## Optimal layout when image is used only as destination of transfer operations
  ImageLayoutPreinitialized = 8  ## Initial layout used when the data is populated by the CPU

type VkAttachmentLoadOp * = enum
  AttachmentLoadOpLoad = 0
  AttachmentLoadOpClear = 1
  AttachmentLoadOpDontCare = 2

type VkAttachmentStoreOp * = enum
  AttachmentStoreOpStore = 0
  AttachmentStoreOpDontCare = 1

type VkImageType * = enum
  ImageType1d = 0
  ImageType2d = 1
  ImageType3d = 2

type VkImageTiling * = enum
  ImageTilingOptimal = 0
  ImageTilingLinear = 1

type VkImageViewType * = enum
  ImageViewType1d = 0
  ImageViewType2d = 1
  ImageViewType3d = 2
  ImageViewTypeCube = 3
  ImageViewType1dArray = 4
  ImageViewType2dArray = 5
  ImageViewTypeCubeArray = 6

type VkCommandBufferLevel * = enum
  CommandBufferLevelPrimary = 0
  CommandBufferLevelSecondary = 1

type VkComponentSwizzle * = enum
  ComponentSwizzleIdentity = 0
  ComponentSwizzleZero = 1
  ComponentSwizzleOne = 2
  ComponentSwizzleR = 3
  ComponentSwizzleG = 4
  ComponentSwizzleB = 5
  ComponentSwizzleA = 6

type VkDescriptorType * = enum
  DescriptorTypeSampler = 0
  DescriptorTypeCombinedImageSampler = 1
  DescriptorTypeSampledImage = 2
  DescriptorTypeStorageImage = 3
  DescriptorTypeUniformTexelBuffer = 4
  DescriptorTypeStorageTexelBuffer = 5
  DescriptorTypeUniformBuffer = 6
  DescriptorTypeStorageBuffer = 7
  DescriptorTypeUniformBufferDynamic = 8
  DescriptorTypeStorageBufferDynamic = 9
  DescriptorTypeInputAttachment = 10

type VkQueryType * = enum
  QueryTypeOcclusion = 0
  QueryTypePipelineStatistics = 1  ## Optional
  QueryTypeTimestamp = 2

type VkBorderColor * = enum
  BorderColorFloatTransparentBlack = 0
  BorderColorIntTransparentBlack = 1
  BorderColorFloatOpaqueBlack = 2
  BorderColorIntOpaqueBlack = 3
  BorderColorFloatOpaqueWhite = 4
  BorderColorIntOpaqueWhite = 5

type VkPipelineBindPoint * = enum
  PipelineBindPointGraphics = 0
  PipelineBindPointCompute = 1

type VkPipelineCacheHeaderVersion * = enum
  PipelineCacheHeaderVersionOne = 1

type VkPrimitiveTopology * = enum
  PrimitiveTopologyPointList = 0
  PrimitiveTopologyLineList = 1
  PrimitiveTopologyLineStrip = 2
  PrimitiveTopologyTriangleList = 3
  PrimitiveTopologyTriangleStrip = 4
  PrimitiveTopologyTriangleFan = 5
  PrimitiveTopologyLineListWithAdjacency = 6
  PrimitiveTopologyLineStripWithAdjacency = 7
  PrimitiveTopologyTriangleListWithAdjacency = 8
  PrimitiveTopologyTriangleStripWithAdjacency = 9
  PrimitiveTopologyPatchList = 10

type VkSharingMode * = enum
  SharingModeExclusive = 0
  SharingModeConcurrent = 1

type VkIndexType * = enum
  IndexTypeUint16 = 0
  IndexTypeUint32 = 1

type VkFilter * = enum
  FilterNearest = 0
  FilterLinear = 1

type VkSamplerMipmapMode * = enum
  SamplerMipmapModeNearest = 0  ## Choose nearest mip level
  SamplerMipmapModeLinear = 1  ## Linear filter between mip levels

type VkSamplerAddressMode * = enum
  SamplerAddressModeRepeat = 0
  SamplerAddressModeMirroredRepeat = 1
  SamplerAddressModeClampToEdge = 2
  SamplerAddressModeClampToBorder = 3

type VkCompareOp * = enum
  CompareOpNever = 0
  CompareOpLess = 1
  CompareOpEqual = 2
  CompareOpLessOrEqual = 3
  CompareOpGreater = 4
  CompareOpNotEqual = 5
  CompareOpGreaterOrEqual = 6
  CompareOpAlways = 7

type VkPolygonMode * = enum
  PolygonModeFill = 0
  PolygonModeLine = 1
  PolygonModePoint = 2

type VkFrontFace * = enum
  FrontFaceCounterClockwise = 0
  FrontFaceClockwise = 1

type VkBlendFactor * = enum
  BlendFactorZero = 0
  BlendFactorOne = 1
  BlendFactorSrcColor = 2
  BlendFactorOneMinusSrcColor = 3
  BlendFactorDstColor = 4
  BlendFactorOneMinusDstColor = 5
  BlendFactorSrcAlpha = 6
  BlendFactorOneMinusSrcAlpha = 7
  BlendFactorDstAlpha = 8
  BlendFactorOneMinusDstAlpha = 9
  BlendFactorConstantColor = 10
  BlendFactorOneMinusConstantColor = 11
  BlendFactorConstantAlpha = 12
  BlendFactorOneMinusConstantAlpha = 13
  BlendFactorSrcAlphaSaturate = 14
  BlendFactorSrc1Color = 15
  BlendFactorOneMinusSrc1Color = 16
  BlendFactorSrc1Alpha = 17
  BlendFactorOneMinusSrc1Alpha = 18

type VkBlendOp * = enum
  BlendOpAdd = 0
  BlendOpSubtract = 1
  BlendOpReverseSubtract = 2
  BlendOpMin = 3
  BlendOpMax = 4

type VkStencilOp * = enum
  StencilOpKeep = 0
  StencilOpZero = 1
  StencilOpReplace = 2
  StencilOpIncrementAndClamp = 3
  StencilOpDecrementAndClamp = 4
  StencilOpInvert = 5
  StencilOpIncrementAndWrap = 6
  StencilOpDecrementAndWrap = 7

type VkLogicOp * = enum
  LogicOpClear = 0
  LogicOpAnd = 1
  LogicOpAndReverse = 2
  LogicOpCopy = 3
  LogicOpAndInverted = 4
  LogicOpNoOp = 5
  LogicOpXor = 6
  LogicOpOr = 7
  LogicOpNor = 8
  LogicOpEquivalent = 9
  LogicOpInvert = 10
  LogicOpOrReverse = 11
  LogicOpCopyInverted = 12
  LogicOpOrInverted = 13
  LogicOpNand = 14
  LogicOpSet = 15

type VkInternalAllocationType * = enum
  InternalAllocationTypeExecutable = 0

type VkSystemAllocationScope * = enum
  SystemAllocationScopeCommand = 0
  SystemAllocationScopeObject = 1
  SystemAllocationScopeCache = 2
  SystemAllocationScopeDevice = 3
  SystemAllocationScopeInstance = 4

type VkPhysicalDeviceType * = enum
  PhysicalDeviceTypeOther = 0
  PhysicalDeviceTypeIntegratedGpu = 1
  PhysicalDeviceTypeDiscreteGpu = 2
  PhysicalDeviceTypeVirtualGpu = 3
  PhysicalDeviceTypeCpu = 4

type VkVertexInputRate * = enum
  VertexInputRateVertex = 0
  VertexInputRateInstance = 1

type VkFormat * = enum
  FormatUndefined = 0
  FormatR4g4UnormPack8 = 1
  FormatR4g4b4a4UnormPack16 = 2
  FormatB4g4r4a4UnormPack16 = 3
  FormatR5g6b5UnormPack16 = 4
  FormatB5g6r5UnormPack16 = 5
  FormatR5g5b5a1UnormPack16 = 6
  FormatB5g5r5a1UnormPack16 = 7
  FormatA1r5g5b5UnormPack16 = 8
  FormatR8Unorm = 9
  FormatR8Snorm = 10
  FormatR8Uscaled = 11
  FormatR8Sscaled = 12
  FormatR8Uint = 13
  FormatR8Sint = 14
  FormatR8Srgb = 15
  FormatR8g8Unorm = 16
  FormatR8g8Snorm = 17
  FormatR8g8Uscaled = 18
  FormatR8g8Sscaled = 19
  FormatR8g8Uint = 20
  FormatR8g8Sint = 21
  FormatR8g8Srgb = 22
  FormatR8g8b8Unorm = 23
  FormatR8g8b8Snorm = 24
  FormatR8g8b8Uscaled = 25
  FormatR8g8b8Sscaled = 26
  FormatR8g8b8Uint = 27
  FormatR8g8b8Sint = 28
  FormatR8g8b8Srgb = 29
  FormatB8g8r8Unorm = 30
  FormatB8g8r8Snorm = 31
  FormatB8g8r8Uscaled = 32
  FormatB8g8r8Sscaled = 33
  FormatB8g8r8Uint = 34
  FormatB8g8r8Sint = 35
  FormatB8g8r8Srgb = 36
  FormatR8g8b8a8Unorm = 37
  FormatR8g8b8a8Snorm = 38
  FormatR8g8b8a8Uscaled = 39
  FormatR8g8b8a8Sscaled = 40
  FormatR8g8b8a8Uint = 41
  FormatR8g8b8a8Sint = 42
  FormatR8g8b8a8Srgb = 43
  FormatB8g8r8a8Unorm = 44
  FormatB8g8r8a8Snorm = 45
  FormatB8g8r8a8Uscaled = 46
  FormatB8g8r8a8Sscaled = 47
  FormatB8g8r8a8Uint = 48
  FormatB8g8r8a8Sint = 49
  FormatB8g8r8a8Srgb = 50
  FormatA8b8g8r8UnormPack32 = 51
  FormatA8b8g8r8SnormPack32 = 52
  FormatA8b8g8r8UscaledPack32 = 53
  FormatA8b8g8r8SscaledPack32 = 54
  FormatA8b8g8r8UintPack32 = 55
  FormatA8b8g8r8SintPack32 = 56
  FormatA8b8g8r8SrgbPack32 = 57
  FormatA2r10g10b10UnormPack32 = 58
  FormatA2r10g10b10SnormPack32 = 59
  FormatA2r10g10b10UscaledPack32 = 60
  FormatA2r10g10b10SscaledPack32 = 61
  FormatA2r10g10b10UintPack32 = 62
  FormatA2r10g10b10SintPack32 = 63
  FormatA2b10g10r10UnormPack32 = 64
  FormatA2b10g10r10SnormPack32 = 65
  FormatA2b10g10r10UscaledPack32 = 66
  FormatA2b10g10r10SscaledPack32 = 67
  FormatA2b10g10r10UintPack32 = 68
  FormatA2b10g10r10SintPack32 = 69
  FormatR16Unorm = 70
  FormatR16Snorm = 71
  FormatR16Uscaled = 72
  FormatR16Sscaled = 73
  FormatR16Uint = 74
  FormatR16Sint = 75
  FormatR16Sfloat = 76
  FormatR16g16Unorm = 77
  FormatR16g16Snorm = 78
  FormatR16g16Uscaled = 79
  FormatR16g16Sscaled = 80
  FormatR16g16Uint = 81
  FormatR16g16Sint = 82
  FormatR16g16Sfloat = 83
  FormatR16g16b16Unorm = 84
  FormatR16g16b16Snorm = 85
  FormatR16g16b16Uscaled = 86
  FormatR16g16b16Sscaled = 87
  FormatR16g16b16Uint = 88
  FormatR16g16b16Sint = 89
  FormatR16g16b16Sfloat = 90
  FormatR16g16b16a16Unorm = 91
  FormatR16g16b16a16Snorm = 92
  FormatR16g16b16a16Uscaled = 93
  FormatR16g16b16a16Sscaled = 94
  FormatR16g16b16a16Uint = 95
  FormatR16g16b16a16Sint = 96
  FormatR16g16b16a16Sfloat = 97
  FormatR32Uint = 98
  FormatR32Sint = 99
  FormatR32Sfloat = 100
  FormatR32g32Uint = 101
  FormatR32g32Sint = 102
  FormatR32g32Sfloat = 103
  FormatR32g32b32Uint = 104
  FormatR32g32b32Sint = 105
  FormatR32g32b32Sfloat = 106
  FormatR32g32b32a32Uint = 107
  FormatR32g32b32a32Sint = 108
  FormatR32g32b32a32Sfloat = 109
  FormatR64Uint = 110
  FormatR64Sint = 111
  FormatR64Sfloat = 112
  FormatR64g64Uint = 113
  FormatR64g64Sint = 114
  FormatR64g64Sfloat = 115
  FormatR64g64b64Uint = 116
  FormatR64g64b64Sint = 117
  FormatR64g64b64Sfloat = 118
  FormatR64g64b64a64Uint = 119
  FormatR64g64b64a64Sint = 120
  FormatR64g64b64a64Sfloat = 121
  FormatB10g11r11UfloatPack32 = 122
  FormatE5b9g9r9UfloatPack32 = 123
  FormatD16Unorm = 124
  FormatX8D24UnormPack32 = 125
  FormatD32Sfloat = 126
  FormatS8Uint = 127
  FormatD16UnormS8Uint = 128
  FormatD24UnormS8Uint = 129
  FormatD32SfloatS8Uint = 130
  FormatBc1RgbUnormBlock = 131
  FormatBc1RgbSrgbBlock = 132
  FormatBc1RgbaUnormBlock = 133
  FormatBc1RgbaSrgbBlock = 134
  FormatBc2UnormBlock = 135
  FormatBc2SrgbBlock = 136
  FormatBc3UnormBlock = 137
  FormatBc3SrgbBlock = 138
  FormatBc4UnormBlock = 139
  FormatBc4SnormBlock = 140
  FormatBc5UnormBlock = 141
  FormatBc5SnormBlock = 142
  FormatBc6hUfloatBlock = 143
  FormatBc6hSfloatBlock = 144
  FormatBc7UnormBlock = 145
  FormatBc7SrgbBlock = 146
  FormatEtc2R8g8b8UnormBlock = 147
  FormatEtc2R8g8b8SrgbBlock = 148
  FormatEtc2R8g8b8a1UnormBlock = 149
  FormatEtc2R8g8b8a1SrgbBlock = 150
  FormatEtc2R8g8b8a8UnormBlock = 151
  FormatEtc2R8g8b8a8SrgbBlock = 152
  FormatEacR11UnormBlock = 153
  FormatEacR11SnormBlock = 154
  FormatEacR11g11UnormBlock = 155
  FormatEacR11g11SnormBlock = 156
  FormatAstc4x4UnormBlock = 157
  FormatAstc4x4SrgbBlock = 158
  FormatAstc5x4UnormBlock = 159
  FormatAstc5x4SrgbBlock = 160
  FormatAstc5x5UnormBlock = 161
  FormatAstc5x5SrgbBlock = 162
  FormatAstc6x5UnormBlock = 163
  FormatAstc6x5SrgbBlock = 164
  FormatAstc6x6UnormBlock = 165
  FormatAstc6x6SrgbBlock = 166
  FormatAstc8x5UnormBlock = 167
  FormatAstc8x5SrgbBlock = 168
  FormatAstc8x6UnormBlock = 169
  FormatAstc8x6SrgbBlock = 170
  FormatAstc8x8UnormBlock = 171
  FormatAstc8x8SrgbBlock = 172
  FormatAstc10x5UnormBlock = 173
  FormatAstc10x5SrgbBlock = 174
  FormatAstc10x6UnormBlock = 175
  FormatAstc10x6SrgbBlock = 176
  FormatAstc10x8UnormBlock = 177
  FormatAstc10x8SrgbBlock = 178
  FormatAstc10x10UnormBlock = 179
  FormatAstc10x10SrgbBlock = 180
  FormatAstc12x10UnormBlock = 181
  FormatAstc12x10SrgbBlock = 182
  FormatAstc12x12UnormBlock = 183
  FormatAstc12x12SrgbBlock = 184

type VkStructureType * = enum
  StructureTypeApplicationInfo = 0
  StructureTypeInstanceCreateInfo = 1
  StructureTypeDeviceQueueCreateInfo = 2
  StructureTypeDeviceCreateInfo = 3
  StructureTypeSubmitInfo = 4
  StructureTypeMemoryAllocateInfo = 5
  StructureTypeMappedMemoryRange = 6
  StructureTypeBindSparseInfo = 7
  StructureTypeFenceCreateInfo = 8
  StructureTypeSemaphoreCreateInfo = 9
  StructureTypeEventCreateInfo = 10
  StructureTypeQueryPoolCreateInfo = 11
  StructureTypeBufferCreateInfo = 12
  StructureTypeBufferViewCreateInfo = 13
  StructureTypeImageCreateInfo = 14
  StructureTypeImageViewCreateInfo = 15
  StructureTypeShaderModuleCreateInfo = 16
  StructureTypePipelineCacheCreateInfo = 17
  StructureTypePipelineShaderStageCreateInfo = 18
  StructureTypePipelineVertexInputStateCreateInfo = 19
  StructureTypePipelineInputAssemblyStateCreateInfo = 20
  StructureTypePipelineTessellationStateCreateInfo = 21
  StructureTypePipelineViewportStateCreateInfo = 22
  StructureTypePipelineRasterizationStateCreateInfo = 23
  StructureTypePipelineMultisampleStateCreateInfo = 24
  StructureTypePipelineDepthStencilStateCreateInfo = 25
  StructureTypePipelineColorBlendStateCreateInfo = 26
  StructureTypePipelineDynamicStateCreateInfo = 27
  StructureTypeGraphicsPipelineCreateInfo = 28
  StructureTypeComputePipelineCreateInfo = 29
  StructureTypePipelineLayoutCreateInfo = 30
  StructureTypeSamplerCreateInfo = 31
  StructureTypeDescriptorSetLayoutCreateInfo = 32
  StructureTypeDescriptorPoolCreateInfo = 33
  StructureTypeDescriptorSetAllocateInfo = 34
  StructureTypeWriteDescriptorSet = 35
  StructureTypeCopyDescriptorSet = 36
  StructureTypeFramebufferCreateInfo = 37
  StructureTypeRenderPassCreateInfo = 38
  StructureTypeCommandPoolCreateInfo = 39
  StructureTypeCommandBufferAllocateInfo = 40
  StructureTypeCommandBufferInheritanceInfo = 41
  StructureTypeCommandBufferBeginInfo = 42
  StructureTypeRenderPassBeginInfo = 43
  StructureTypeBufferMemoryBarrier = 44
  StructureTypeImageMemoryBarrier = 45
  StructureTypeMemoryBarrier = 46
  StructureTypeLoaderInstanceCreateInfo = 47  ## Reserved for internal use by the loader, layers, and ICDs
  StructureTypeLoaderDeviceCreateInfo = 48  ## Reserved for internal use by the loader, layers, and ICDs

type VkSubpassContents * = enum
  SubpassContentsInline = 0
  SubpassContentsSecondaryCommandBuffers = 1

type VkResult * = enum
  ErrorUnknown = -13  ## An unknown error has occurred, due to an implementation or application bug
  ErrorFragmentedPool = -12  ## A requested pool allocation has failed due to fragmentation of the pool's memory
  ErrorFormatNotSupported = -11  ## Requested format is not supported on this device
  ErrorTooManyObjects = -10  ## Too many objects of the type have already been created
  ErrorIncompatibleDriver = -9  ## Unable to find a Vulkan driver
  ErrorFeatureNotPresent = -8  ## Requested feature is not available on this device
  ErrorExtensionNotPresent = -7  ## Extension specified does not exist
  ErrorLayerNotPresent = -6  ## Layer specified does not exist
  ErrorMemoryMapFailed = -5  ## Mapping of a memory object has failed
  ErrorDeviceLost = -4  ## The logical device has been lost. See <<devsandqueues-lost-device>>
  ErrorInitializationFailed = -3  ## Initialization of an object has failed
  ErrorOutOfDeviceMemory = -2  ## A device memory allocation has failed
  ErrorOutOfHostMemory = -1  ## A host memory allocation has failed
  Success = 0  ## Command completed successfully
  NotReady = 1  ## A fence or query has not yet completed
  Timeout = 2  ## A wait operation has not completed in the specified time
  EventSet = 3  ## An event is signaled
  EventReset = 4  ## An event is unsignaled
  Incomplete = 5  ## A return array was too small for the result

type VkDynamicState * = enum
  DynamicStateViewport = 0
  DynamicStateScissor = 1
  DynamicStateLineWidth = 2
  DynamicStateDepthBias = 3
  DynamicStateBlendConstants = 4
  DynamicStateDepthBounds = 5
  DynamicStateStencilCompareMask = 6
  DynamicStateStencilWriteMask = 7
  DynamicStateStencilReference = 8

type VkDescriptorUpdateTemplateType * = enum
  DescriptorUpdateTemplateTypeDescriptorSet = 0  ## Create descriptor update template for descriptor set updates

type VkObjectType * = enum
  ObjectTypeUnknown = 0
  ObjectTypeInstance = 1
  ObjectTypePhysicalDevice = 2
  ObjectTypeDevice = 3
  ObjectTypeQueue = 4
  ObjectTypeSemaphore = 5
  ObjectTypeCommandBuffer = 6
  ObjectTypeFence = 7
  ObjectTypeDeviceMemory = 8
  ObjectTypeBuffer = 9
  ObjectTypeImage = 10
  ObjectTypeEvent = 11
  ObjectTypeQueryPool = 12
  ObjectTypeBufferView = 13
  ObjectTypeImageView = 14
  ObjectTypeShaderModule = 15
  ObjectTypePipelineCache = 16
  ObjectTypePipelineLayout = 17
  ObjectTypeRenderPass = 18
  ObjectTypePipeline = 19
  ObjectTypeDescriptorSetLayout = 20
  ObjectTypeSampler = 21
  ObjectTypeDescriptorPool = 22
  ObjectTypeDescriptorSet = 23
  ObjectTypeFramebuffer = 24
  ObjectTypeCommandPool = 25

type VkRayTracingInvocationReorderModeNV * = enum
  RayTracingInvocationReorderModeNoneNv = 0
  RayTracingInvocationReorderModeReorderNv = 1

type VkDirectDriverLoadingModeLUNARG * = enum
  DirectDriverLoadingModeExclusiveLunarg = 0
  DirectDriverLoadingModeInclusiveLunarg = 1

type VkSemaphoreType * = enum
  SemaphoreTypeBinary = 0
  SemaphoreTypeTimeline = 1

type VkPresentModeKHR * = enum
  PresentModeImmediateKhr = 0
  PresentModeMailboxKhr = 1
  PresentModeFifoKhr = 2
  PresentModeFifoRelaxedKhr = 3

type VkColorSpaceKHR * = enum
  ColorSpaceSrgbNonlinearKhr = 0

type VkTimeDomainKHR * = enum
  TimeDomainDeviceKhr = 0
  TimeDomainClockMonotonicKhr = 1
  TimeDomainClockMonotonicRawKhr = 2
  TimeDomainQueryPerformanceCounterKhr = 3

type VkDebugReportObjectTypeEXT * = enum
  DebugReportObjectTypeUnknownExt = 0
  DebugReportObjectTypeInstanceExt = 1
  DebugReportObjectTypePhysicalDeviceExt = 2
  DebugReportObjectTypeDeviceExt = 3
  DebugReportObjectTypeQueueExt = 4
  DebugReportObjectTypeSemaphoreExt = 5
  DebugReportObjectTypeCommandBufferExt = 6
  DebugReportObjectTypeFenceExt = 7
  DebugReportObjectTypeDeviceMemoryExt = 8
  DebugReportObjectTypeBufferExt = 9
  DebugReportObjectTypeImageExt = 10
  DebugReportObjectTypeEventExt = 11
  DebugReportObjectTypeQueryPoolExt = 12
  DebugReportObjectTypeBufferViewExt = 13
  DebugReportObjectTypeImageViewExt = 14
  DebugReportObjectTypeShaderModuleExt = 15
  DebugReportObjectTypePipelineCacheExt = 16
  DebugReportObjectTypePipelineLayoutExt = 17
  DebugReportObjectTypeRenderPassExt = 18
  DebugReportObjectTypePipelineExt = 19
  DebugReportObjectTypeDescriptorSetLayoutExt = 20
  DebugReportObjectTypeSamplerExt = 21
  DebugReportObjectTypeDescriptorPoolExt = 22
  DebugReportObjectTypeDescriptorSetExt = 23
  DebugReportObjectTypeFramebufferExt = 24
  DebugReportObjectTypeCommandPoolExt = 25
  DebugReportObjectTypeSurfaceKhrExt = 26
  DebugReportObjectTypeSwapchainKhrExt = 27
  DebugReportObjectTypeDebugReportCallbackExtExt = 28
  DebugReportObjectTypeDisplayKhrExt = 29
  DebugReportObjectTypeDisplayModeKhrExt = 30
  DebugReportObjectTypeValidationCacheExtExt = 33

type VkDeviceMemoryReportEventTypeEXT * = enum
  DeviceMemoryReportEventTypeAllocateExt = 0
  DeviceMemoryReportEventTypeFreeExt = 1
  DeviceMemoryReportEventTypeImportExt = 2
  DeviceMemoryReportEventTypeUnimportExt = 3
  DeviceMemoryReportEventTypeAllocationFailedExt = 4

type VkRasterizationOrderAMD * = enum
  RasterizationOrderStrictAmd = 0
  RasterizationOrderRelaxedAmd = 1

type VkValidationCheckEXT * = enum
  ValidationCheckAllExt = 0
  ValidationCheckShadersExt = 1

type VkValidationFeatureEnableEXT * = enum
  ValidationFeatureEnableGpuAssistedExt = 0
  ValidationFeatureEnableGpuAssistedReserveBindingSlotExt = 1
  ValidationFeatureEnableBestPracticesExt = 2
  ValidationFeatureEnableDebugPrintfExt = 3
  ValidationFeatureEnableSynchronizationValidationExt = 4

type VkValidationFeatureDisableEXT * = enum
  ValidationFeatureDisableAllExt = 0
  ValidationFeatureDisableShadersExt = 1
  ValidationFeatureDisableThreadSafetyExt = 2
  ValidationFeatureDisableApiParametersExt = 3
  ValidationFeatureDisableObjectLifetimesExt = 4
  ValidationFeatureDisableCoreChecksExt = 5
  ValidationFeatureDisableUniqueHandlesExt = 6
  ValidationFeatureDisableShaderValidationCacheExt = 7

type VkLayerSettingTypeEXT * = enum
  LayerSettingTypeBool32Ext = 0
  LayerSettingTypeInt32Ext = 1
  LayerSettingTypeInt64Ext = 2
  LayerSettingTypeUint32Ext = 3
  LayerSettingTypeUint64Ext = 4
  LayerSettingTypeFloat32Ext = 5
  LayerSettingTypeFloat64Ext = 6
  LayerSettingTypeStringExt = 7

type VkIndirectCommandsTokenTypeNV * = enum
  IndirectCommandsTokenTypeShaderGroupNv = 0
  IndirectCommandsTokenTypeStateFlagsNv = 1
  IndirectCommandsTokenTypeIndexBufferNv = 2
  IndirectCommandsTokenTypeVertexBufferNv = 3
  IndirectCommandsTokenTypePushConstantNv = 4
  IndirectCommandsTokenTypeDrawIndexedNv = 5
  IndirectCommandsTokenTypeDrawNv = 6
  IndirectCommandsTokenTypeDrawTasksNv = 7

type VkDisplayPowerStateEXT * = enum
  DisplayPowerStateOffExt = 0
  DisplayPowerStateSuspendExt = 1
  DisplayPowerStateOnExt = 2

type VkDeviceEventTypeEXT * = enum
  DeviceEventTypeDisplayHotplugExt = 0

type VkDisplayEventTypeEXT * = enum
  DisplayEventTypeFirstPixelOutExt = 0

type VkViewportCoordinateSwizzleNV * = enum
  ViewportCoordinateSwizzlePositiveXNv = 0
  ViewportCoordinateSwizzleNegativeXNv = 1
  ViewportCoordinateSwizzlePositiveYNv = 2
  ViewportCoordinateSwizzleNegativeYNv = 3
  ViewportCoordinateSwizzlePositiveZNv = 4
  ViewportCoordinateSwizzleNegativeZNv = 5
  ViewportCoordinateSwizzlePositiveWNv = 6
  ViewportCoordinateSwizzleNegativeWNv = 7

type VkDiscardRectangleModeEXT * = enum
  DiscardRectangleModeInclusiveExt = 0
  DiscardRectangleModeExclusiveExt = 1

type VkPointClippingBehavior * = enum
  PointClippingBehaviorAllClipPlanes = 0
  PointClippingBehaviorUserClipPlanesOnly = 1

type VkSamplerReductionMode * = enum
  SamplerReductionModeWeightedAverage = 0
  SamplerReductionModeMin = 1
  SamplerReductionModeMax = 2

type VkTessellationDomainOrigin * = enum
  TessellationDomainOriginUpperLeft = 0
  TessellationDomainOriginLowerLeft = 1

type VkSamplerYcbcrModelConversion * = enum
  SamplerYcbcrModelConversionRgbIdentity = 0
  SamplerYcbcrModelConversionYcbcrIdentity = 1  ## just range expansion
  SamplerYcbcrModelConversionYcbcr709 = 2  ## aka HD YUV
  SamplerYcbcrModelConversionYcbcr601 = 3  ## aka SD YUV
  SamplerYcbcrModelConversionYcbcr2020 = 4  ## aka UHD YUV

type VkSamplerYcbcrRange * = enum
  SamplerYcbcrRangeItuFull = 0  ## Luma 0..1 maps to 0..255, chroma -0.5..0.5 to 1..255 (clamped)
  SamplerYcbcrRangeItuNarrow = 1  ## Luma 0..1 maps to 16..235, chroma -0.5..0.5 to 16..240

type VkChromaLocation * = enum
  ChromaLocationCositedEven = 0
  ChromaLocationMidpoint = 1

type VkBlendOverlapEXT * = enum
  BlendOverlapUncorrelatedExt = 0
  BlendOverlapDisjointExt = 1
  BlendOverlapConjointExt = 2

type VkCoverageModulationModeNV * = enum
  CoverageModulationModeNoneNv = 0
  CoverageModulationModeRgbNv = 1
  CoverageModulationModeAlphaNv = 2
  CoverageModulationModeRgbaNv = 3

type VkCoverageReductionModeNV * = enum
  CoverageReductionModeMergeNv = 0
  CoverageReductionModeTruncateNv = 1

type VkValidationCacheHeaderVersionEXT * = enum
  ValidationCacheHeaderVersionOneExt = 1

type VkShaderInfoTypeAMD * = enum
  ShaderInfoTypeStatisticsAmd = 0
  ShaderInfoTypeBinaryAmd = 1
  ShaderInfoTypeDisassemblyAmd = 2

type VkQueueGlobalPriorityKHR * = enum
  QueueGlobalPriorityLowKhr = 128
  QueueGlobalPriorityMediumKhr = 256
  QueueGlobalPriorityHighKhr = 512
  QueueGlobalPriorityRealtimeKhr = 1024

type VkConservativeRasterizationModeEXT * = enum
  ConservativeRasterizationModeDisabledExt = 0
  ConservativeRasterizationModeOverestimateExt = 1
  ConservativeRasterizationModeUnderestimateExt = 2

type VkVendorId * = enum
  VendorIdViv = 0x10001  ## Vivante vendor ID
  VendorIdVsi = 0x10002  ## VeriSilicon vendor ID
  VendorIdKazan = 0x10003  ## Kazan Software Renderer
  VendorIdCodeplay = 0x10004  ## Codeplay Software Ltd. vendor ID
  VendorIdMesa = 0x10005  ## Mesa vendor ID
  VendorIdPocl = 0x10006  ## PoCL vendor ID
  VendorIdMobileye = 0x10007  ## Mobileye vendor ID

type VkDriverId * = enum
  DriverIdAmdProprietary = 1  ## Advanced Micro Devices, Inc.
  DriverIdAmdOpenSource = 2  ## Advanced Micro Devices, Inc.
  DriverIdMesaRadv = 3  ## Mesa open source project
  DriverIdNvidiaProprietary = 4  ## NVIDIA Corporation
  DriverIdIntelProprietaryWindows = 5  ## Intel Corporation
  DriverIdIntelOpenSourceMesa = 6  ## Intel Corporation
  DriverIdImaginationProprietary = 7  ## Imagination Technologies
  DriverIdQualcommProprietary = 8  ## Qualcomm Technologies, Inc.
  DriverIdArmProprietary = 9  ## Arm Limited
  DriverIdGoogleSwiftshader = 10  ## Google LLC
  DriverIdGgpProprietary = 11  ## Google LLC
  DriverIdBroadcomProprietary = 12  ## Broadcom Inc.
  DriverIdMesaLlvmpipe = 13  ## Mesa
  DriverIdMoltenvk = 14  ## MoltenVK
  DriverIdCoreaviProprietary = 15  ## Core Avionics & Industrial Inc.
  DriverIdJuiceProprietary = 16  ## Juice Technologies, Inc.
  DriverIdVerisiliconProprietary = 17  ## Verisilicon, Inc.
  DriverIdMesaTurnip = 18  ## Mesa open source project
  DriverIdMesaV3dv = 19  ## Mesa open source project
  DriverIdMesaPanvk = 20  ## Mesa open source project
  DriverIdSamsungProprietary = 21  ## Samsung Electronics Co., Ltd.
  DriverIdMesaVenus = 22  ## Mesa open source project
  DriverIdMesaDozen = 23  ## Mesa open source project
  DriverIdMesaNvk = 24  ## Mesa open source project
  DriverIdImaginationOpenSourceMesa = 25  ## Imagination Technologies
  DriverIdMesaAgxv = 26  ## Mesa open source project

type VkShadingRatePaletteEntryNV * = enum
  ShadingRatePaletteEntryNoInvocationsNv = 0
  ShadingRatePaletteEntry16InvocationsPerPixelNv = 1
  ShadingRatePaletteEntry8InvocationsPerPixelNv = 2
  ShadingRatePaletteEntry4InvocationsPerPixelNv = 3
  ShadingRatePaletteEntry2InvocationsPerPixelNv = 4
  ShadingRatePaletteEntry1InvocationPerPixelNv = 5
  ShadingRatePaletteEntry1InvocationPer2x1PixelsNv = 6
  ShadingRatePaletteEntry1InvocationPer1x2PixelsNv = 7
  ShadingRatePaletteEntry1InvocationPer2x2PixelsNv = 8
  ShadingRatePaletteEntry1InvocationPer4x2PixelsNv = 9
  ShadingRatePaletteEntry1InvocationPer2x4PixelsNv = 10
  ShadingRatePaletteEntry1InvocationPer4x4PixelsNv = 11

type VkCoarseSampleOrderTypeNV * = enum
  CoarseSampleOrderTypeDefaultNv = 0
  CoarseSampleOrderTypeCustomNv = 1
  CoarseSampleOrderTypePixelMajorNv = 2
  CoarseSampleOrderTypeSampleMajorNv = 3

type VkCopyAccelerationStructureModeKHR * = enum
  CopyAccelerationStructureModeCloneKhr = 0
  CopyAccelerationStructureModeCompactKhr = 1
  CopyAccelerationStructureModeSerializeKhr = 2
  CopyAccelerationStructureModeDeserializeKhr = 3

type VkBuildAccelerationStructureModeKHR * = enum
  BuildAccelerationStructureModeBuildKhr = 0
  BuildAccelerationStructureModeUpdateKhr = 1

type VkAccelerationStructureTypeKHR * = enum
  AccelerationStructureTypeTopLevelKhr = 0
  AccelerationStructureTypeBottomLevelKhr = 1
  AccelerationStructureTypeGenericKhr = 2

type VkGeometryTypeKHR * = enum
  GeometryTypeTrianglesKhr = 0
  GeometryTypeAabbsKhr = 1
  GeometryTypeInstancesKhr = 2

type VkAccelerationStructureMemoryRequirementsTypeNV * = enum
  AccelerationStructureMemoryRequirementsTypeObjectNv = 0
  AccelerationStructureMemoryRequirementsTypeBuildScratchNv = 1
  AccelerationStructureMemoryRequirementsTypeUpdateScratchNv = 2

type VkAccelerationStructureBuildTypeKHR * = enum
  AccelerationStructureBuildTypeHostKhr = 0
  AccelerationStructureBuildTypeDeviceKhr = 1
  AccelerationStructureBuildTypeHostOrDeviceKhr = 2

type VkRayTracingShaderGroupTypeKHR * = enum
  RayTracingShaderGroupTypeGeneralKhr = 0
  RayTracingShaderGroupTypeTrianglesHitGroupKhr = 1
  RayTracingShaderGroupTypeProceduralHitGroupKhr = 2

type VkAccelerationStructureCompatibilityKHR * = enum
  AccelerationStructureCompatibilityCompatibleKhr = 0
  AccelerationStructureCompatibilityIncompatibleKhr = 1

type VkShaderGroupShaderKHR * = enum
  ShaderGroupShaderGeneralKhr = 0
  ShaderGroupShaderClosestHitKhr = 1
  ShaderGroupShaderAnyHitKhr = 2
  ShaderGroupShaderIntersectionKhr = 3

type VkMemoryOverallocationBehaviorAMD * = enum
  MemoryOverallocationBehaviorDefaultAmd = 0
  MemoryOverallocationBehaviorAllowedAmd = 1
  MemoryOverallocationBehaviorDisallowedAmd = 2

type VkFullScreenExclusiveEXT * = enum
  FullScreenExclusiveDefaultExt = 0
  FullScreenExclusiveAllowedExt = 1
  FullScreenExclusiveDisallowedExt = 2
  FullScreenExclusiveApplicationControlledExt = 3

type VkPerformanceCounterScopeKHR * = enum
  PerformanceCounterScopeCommandBufferKhr = 0
  PerformanceCounterScopeRenderPassKhr = 1
  PerformanceCounterScopeCommandKhr = 2

type VkPerformanceCounterUnitKHR * = enum
  PerformanceCounterUnitGenericKhr = 0
  PerformanceCounterUnitPercentageKhr = 1
  PerformanceCounterUnitNanosecondsKhr = 2
  PerformanceCounterUnitBytesKhr = 3
  PerformanceCounterUnitBytesPerSecondKhr = 4
  PerformanceCounterUnitKelvinKhr = 5
  PerformanceCounterUnitWattsKhr = 6
  PerformanceCounterUnitVoltsKhr = 7
  PerformanceCounterUnitAmpsKhr = 8
  PerformanceCounterUnitHertzKhr = 9
  PerformanceCounterUnitCyclesKhr = 10

type VkPerformanceCounterStorageKHR * = enum
  PerformanceCounterStorageInt32Khr = 0
  PerformanceCounterStorageInt64Khr = 1
  PerformanceCounterStorageUint32Khr = 2
  PerformanceCounterStorageUint64Khr = 3
  PerformanceCounterStorageFloat32Khr = 4
  PerformanceCounterStorageFloat64Khr = 5

type VkPerformanceConfigurationTypeINTEL * = enum
  PerformanceConfigurationTypeCommandQueueMetricsDiscoveryActivatedIntel = 0

type VkQueryPoolSamplingModeINTEL * = enum
  QueryPoolSamplingModeManualIntel = 0

type VkPerformanceOverrideTypeINTEL * = enum
  PerformanceOverrideTypeNullHardwareIntel = 0
  PerformanceOverrideTypeFlushGpuCachesIntel = 1

type VkPerformanceParameterTypeINTEL * = enum
  PerformanceParameterTypeHwCountersSupportedIntel = 0
  PerformanceParameterTypeStreamMarkerValidBitsIntel = 1

type VkPerformanceValueTypeINTEL * = enum
  PerformanceValueTypeUint32Intel = 0
  PerformanceValueTypeUint64Intel = 1
  PerformanceValueTypeFloatIntel = 2
  PerformanceValueTypeBoolIntel = 3
  PerformanceValueTypeStringIntel = 4

type VkShaderFloatControlsIndependence * = enum
  ShaderFloatControlsIndependence32BitOnly = 0
  ShaderFloatControlsIndependenceAll = 1
  ShaderFloatControlsIndependenceNone = 2

type VkPipelineExecutableStatisticFormatKHR * = enum
  PipelineExecutableStatisticFormatBool32Khr = 0
  PipelineExecutableStatisticFormatInt64Khr = 1
  PipelineExecutableStatisticFormatUint64Khr = 2
  PipelineExecutableStatisticFormatFloat64Khr = 3

type VkLineRasterizationModeKHR * = enum
  LineRasterizationModeDefaultKhr = 0
  LineRasterizationModeRectangularKhr = 1
  LineRasterizationModeBresenhamKhr = 2
  LineRasterizationModeRectangularSmoothKhr = 3

type VkFaultLevel * = enum
  FaultLevelUnassigned = 0
  FaultLevelCritical = 1
  FaultLevelRecoverable = 2
  FaultLevelWarning = 3

type VkFaultType * = enum
  FaultTypeInvalid = 0
  FaultTypeUnassigned = 1
  FaultTypeImplementation = 2
  FaultTypeSystem = 3
  FaultTypePhysicalDevice = 4
  FaultTypeCommandBufferFull = 5
  FaultTypeInvalidApiUsage = 6

type VkFaultQueryBehavior * = enum
  FaultQueryBehaviorGetAndClearAllFaults = 0

type VkPipelineMatchControl * = enum
  PipelineMatchControlApplicationUuidExactMatch = 0

type VkFragmentShadingRateCombinerOpKHR * = enum
  FragmentShadingRateCombinerOpKeepKhr = 0
  FragmentShadingRateCombinerOpReplaceKhr = 1
  FragmentShadingRateCombinerOpMinKhr = 2
  FragmentShadingRateCombinerOpMaxKhr = 3
  FragmentShadingRateCombinerOpMulKhr = 4

type VkFragmentShadingRateNV * = enum
  FragmentShadingRate1InvocationPerPixelNv = 0
  FragmentShadingRate1InvocationPer1x2PixelsNv = 1
  FragmentShadingRate1InvocationPer2x1PixelsNv = 4
  FragmentShadingRate1InvocationPer2x2PixelsNv = 5
  FragmentShadingRate1InvocationPer2x4PixelsNv = 6
  FragmentShadingRate1InvocationPer4x2PixelsNv = 9
  FragmentShadingRate1InvocationPer4x4PixelsNv = 10
  FragmentShadingRate2InvocationsPerPixelNv = 11
  FragmentShadingRate4InvocationsPerPixelNv = 12
  FragmentShadingRate8InvocationsPerPixelNv = 13
  FragmentShadingRate16InvocationsPerPixelNv = 14
  FragmentShadingRateNoInvocationsNv = 15

type VkFragmentShadingRateTypeNV * = enum
  FragmentShadingRateTypeFragmentSizeNv = 0
  FragmentShadingRateTypeEnumsNv = 1

type VkSubpassMergeStatusEXT * = enum
  SubpassMergeStatusMergedExt = 0
  SubpassMergeStatusDisallowedExt = 1
  SubpassMergeStatusNotMergedSideEffectsExt = 2
  SubpassMergeStatusNotMergedSamplesMismatchExt = 3
  SubpassMergeStatusNotMergedViewsMismatchExt = 4
  SubpassMergeStatusNotMergedAliasingExt = 5
  SubpassMergeStatusNotMergedDependenciesExt = 6
  SubpassMergeStatusNotMergedIncompatibleInputAttachmentExt = 7
  SubpassMergeStatusNotMergedTooManyAttachmentsExt = 8
  SubpassMergeStatusNotMergedInsufficientStorageExt = 9
  SubpassMergeStatusNotMergedDepthStencilCountExt = 10
  SubpassMergeStatusNotMergedResolveAttachmentReuseExt = 11
  SubpassMergeStatusNotMergedSingleSubpassExt = 12
  SubpassMergeStatusNotMergedUnspecifiedExt = 13

type VkSciSyncClientTypeNV * = enum
  SciSyncClientTypeSignalerNv = 0
  SciSyncClientTypeWaiterNv = 1
  SciSyncClientTypeSignalerWaiterNv = 2

type VkSciSyncPrimitiveTypeNV * = enum
  SciSyncPrimitiveTypeFenceNv = 0
  SciSyncPrimitiveTypeSemaphoreNv = 1

type VkProvokingVertexModeEXT * = enum
  ProvokingVertexModeFirstVertexExt = 0
  ProvokingVertexModeLastVertexExt = 1

type VkPipelineCacheValidationVersion * = enum
  PipelineCacheValidationVersionSafetyCriticalOne = 1

type VkAccelerationStructureMotionInstanceTypeNV * = enum
  AccelerationStructureMotionInstanceTypeStaticNv = 0
  AccelerationStructureMotionInstanceTypeMatrixMotionNv = 1
  AccelerationStructureMotionInstanceTypeSrtMotionNv = 2

type VkDeviceAddressBindingTypeEXT * = enum
  DeviceAddressBindingTypeBindExt = 0
  DeviceAddressBindingTypeUnbindExt = 1

type VkQueryResultStatusKHR * = enum
  QueryResultStatusErrorKhr = -1
  QueryResultStatusNotReadyKhr = 0
  QueryResultStatusCompleteKhr = 1

type VkVideoEncodeTuningModeKHR * = enum
  VideoEncodeTuningModeDefaultKhr = 0
  VideoEncodeTuningModeHighQualityKhr = 1
  VideoEncodeTuningModeLowLatencyKhr = 2
  VideoEncodeTuningModeUltraLowLatencyKhr = 3
  VideoEncodeTuningModeLosslessKhr = 4

type VkPipelineRobustnessBufferBehaviorEXT * = enum
  PipelineRobustnessBufferBehaviorDeviceDefaultExt = 0
  PipelineRobustnessBufferBehaviorDisabledExt = 1
  PipelineRobustnessBufferBehaviorRobustBufferAccessExt = 2
  PipelineRobustnessBufferBehaviorRobustBufferAccess2Ext = 3

type VkPipelineRobustnessImageBehaviorEXT * = enum
  PipelineRobustnessImageBehaviorDeviceDefaultExt = 0
  PipelineRobustnessImageBehaviorDisabledExt = 1
  PipelineRobustnessImageBehaviorRobustImageAccessExt = 2
  PipelineRobustnessImageBehaviorRobustImageAccess2Ext = 3

type VkOpticalFlowPerformanceLevelNV * = enum
  OpticalFlowPerformanceLevelUnknownNv = 0
  OpticalFlowPerformanceLevelSlowNv = 1
  OpticalFlowPerformanceLevelMediumNv = 2
  OpticalFlowPerformanceLevelFastNv = 3

type VkOpticalFlowSessionBindingPointNV * = enum
  OpticalFlowSessionBindingPointUnknownNv = 0
  OpticalFlowSessionBindingPointInputNv = 1
  OpticalFlowSessionBindingPointReferenceNv = 2
  OpticalFlowSessionBindingPointHintNv = 3
  OpticalFlowSessionBindingPointFlowVectorNv = 4
  OpticalFlowSessionBindingPointBackwardFlowVectorNv = 5
  OpticalFlowSessionBindingPointCostNv = 6
  OpticalFlowSessionBindingPointBackwardCostNv = 7
  OpticalFlowSessionBindingPointGlobalFlowNv = 8

type VkMicromapTypeEXT * = enum
  MicromapTypeOpacityMicromapExt = 0

type VkCopyMicromapModeEXT * = enum
  CopyMicromapModeCloneExt = 0
  CopyMicromapModeSerializeExt = 1
  CopyMicromapModeDeserializeExt = 2
  CopyMicromapModeCompactExt = 3

type VkBuildMicromapModeEXT * = enum
  BuildMicromapModeBuildExt = 0

type VkOpacityMicromapFormatEXT * = enum
  OpacityMicromapFormat2StateExt = 1
  OpacityMicromapFormat4StateExt = 2

type VkOpacityMicromapSpecialIndexEXT * = enum
  OpacityMicromapSpecialIndexFullyUnknownOpaqueExt = -4
  OpacityMicromapSpecialIndexFullyUnknownTransparentExt = -3
  OpacityMicromapSpecialIndexFullyOpaqueExt = -2
  OpacityMicromapSpecialIndexFullyTransparentExt = -1

type VkDepthBiasRepresentationEXT * = enum
  DepthBiasRepresentationLeastRepresentableValueFormatExt = 0
  DepthBiasRepresentationLeastRepresentableValueForceUnormExt = 1
  DepthBiasRepresentationFloatExt = 2

type VkDeviceFaultAddressTypeEXT * = enum
  DeviceFaultAddressTypeNoneExt = 0  ## Currently unused
  DeviceFaultAddressTypeReadInvalidExt = 1
  DeviceFaultAddressTypeWriteInvalidExt = 2
  DeviceFaultAddressTypeExecuteInvalidExt = 3
  DeviceFaultAddressTypeInstructionPointerUnknownExt = 4
  DeviceFaultAddressTypeInstructionPointerInvalidExt = 5
  DeviceFaultAddressTypeInstructionPointerFaultExt = 6

type VkDeviceFaultVendorBinaryHeaderVersionEXT * = enum
  DeviceFaultVendorBinaryHeaderVersionOneExt = 1

type VkDisplacementMicromapFormatNV * = enum
  DisplacementMicromapFormat64Triangles64BytesNv = 1
  DisplacementMicromapFormat256Triangles128BytesNv = 2
  DisplacementMicromapFormat1024Triangles128BytesNv = 3

type VkShaderCodeTypeEXT * = enum
  ShaderCodeTypeBinaryExt = 0
  ShaderCodeTypeSpirvExt = 1

type VkScopeKHR * = enum
  ScopeDeviceKhr = 1
  ScopeWorkgroupKhr = 2
  ScopeSubgroupKhr = 3
  ScopeQueueFamilyKhr = 5

type VkComponentTypeKHR * = enum
  ComponentTypeFloat16Khr = 0
  ComponentTypeFloat32Khr = 1
  ComponentTypeFloat64Khr = 2
  ComponentTypeSint8Khr = 3
  ComponentTypeSint16Khr = 4
  ComponentTypeSint32Khr = 5
  ComponentTypeSint64Khr = 6
  ComponentTypeUint8Khr = 7
  ComponentTypeUint16Khr = 8
  ComponentTypeUint32Khr = 9
  ComponentTypeUint64Khr = 10

type VkCubicFilterWeightsQCOM * = enum
  CubicFilterWeightsCatmullRomQcom = 0
  CubicFilterWeightsZeroTangentCardinalQcom = 1
  CubicFilterWeightsBSplineQcom = 2
  CubicFilterWeightsMitchellNetravaliQcom = 3

type VkBlockMatchWindowCompareModeQCOM * = enum
  BlockMatchWindowCompareModeMinQcom = 0
  BlockMatchWindowCompareModeMaxQcom = 1

type VkLayeredDriverUnderlyingApiMSFT * = enum
  LayeredDriverUnderlyingApiNoneMsft = 0
  LayeredDriverUnderlyingApiD3d12Msft = 1

type VkLatencyMarkerNV * = enum
  LatencyMarkerSimulationStartNv = 0
  LatencyMarkerSimulationEndNv = 1
  LatencyMarkerRendersubmitStartNv = 2
  LatencyMarkerRendersubmitEndNv = 3
  LatencyMarkerPresentStartNv = 4
  LatencyMarkerPresentEndNv = 5
  LatencyMarkerInputSampleNv = 6
  LatencyMarkerTriggerFlashNv = 7
  LatencyMarkerOutOfBandRendersubmitStartNv = 8
  LatencyMarkerOutOfBandRendersubmitEndNv = 9
  LatencyMarkerOutOfBandPresentStartNv = 10
  LatencyMarkerOutOfBandPresentEndNv = 11

type VkOutOfBandQueueTypeNV * = enum
  OutOfBandQueueTypeRenderNv = 0
  OutOfBandQueueTypePresentNv = 1

## Value Bitmasks
type VkQueueFlagBits * = enum
  QueueGraphicsBit = 1  ## Queue supports graphics operations
  QueueComputeBit = 2  ## Queue supports compute operations
  QueueTransferBit = 4  ## Queue supports transfer operations
  QueueSparseBindingBit = 8  ## Queue supports sparse resource memory management operations

type VkCullModeFlagBits * = enum
  CullModeNone = 0
  CullModeFrontBit = 1
  CullModeBackBit = 2
  CullModeFrontAndBack = 0x00000003

type VkMemoryPropertyFlagBits * = enum
  MemoryPropertyDeviceLocalBit = 1  ## If otherwise stated, then allocate memory on device
  MemoryPropertyHostVisibleBit = 2  ## Memory is mappable by host
  MemoryPropertyHostCoherentBit = 4  ## Memory will have i/o coherency. If not set, application may need to use vkFlushMappedMemoryRanges and vkInvalidateMappedMemoryRanges to flush/invalidate host cache
  MemoryPropertyHostCachedBit = 8  ## Memory will be cached by the host
  MemoryPropertyLazilyAllocatedBit = 16  ## Memory may be allocated by the driver when it is required

type VkMemoryHeapFlagBits * = enum
  MemoryHeapDeviceLocalBit = 1  ## If set, heap represents device memory

type VkAccessFlagBits * = enum
  AccessIndirectCommandReadBit = 1  ## Controls coherency of indirect command reads
  AccessIndexReadBit = 2  ## Controls coherency of index reads
  AccessVertexAttributeReadBit = 4  ## Controls coherency of vertex attribute reads
  AccessUniformReadBit = 8  ## Controls coherency of uniform buffer reads
  AccessInputAttachmentReadBit = 16  ## Controls coherency of input attachment reads
  AccessShaderReadBit = 32  ## Controls coherency of shader reads
  AccessShaderWriteBit = 64  ## Controls coherency of shader writes
  AccessColorAttachmentReadBit = 128  ## Controls coherency of color attachment reads
  AccessColorAttachmentWriteBit = 256  ## Controls coherency of color attachment writes
  AccessDepthStencilAttachmentReadBit = 512  ## Controls coherency of depth/stencil attachment reads
  AccessDepthStencilAttachmentWriteBit = 1024  ## Controls coherency of depth/stencil attachment writes
  AccessTransferReadBit = 2048  ## Controls coherency of transfer reads
  AccessTransferWriteBit = 4096  ## Controls coherency of transfer writes
  AccessHostReadBit = 8192  ## Controls coherency of host reads
  AccessHostWriteBit = 16384  ## Controls coherency of host writes
  AccessMemoryReadBit = 32768  ## Controls coherency of memory reads
  AccessMemoryWriteBit = 65536  ## Controls coherency of memory writes

type VkBufferUsageFlagBits * = enum
  BufferUsageTransferSrcBit = 1  ## Can be used as a source of transfer operations
  BufferUsageTransferDstBit = 2  ## Can be used as a destination of transfer operations
  BufferUsageUniformTexelBufferBit = 4  ## Can be used as TBO
  BufferUsageStorageTexelBufferBit = 8  ## Can be used as IBO
  BufferUsageUniformBufferBit = 16  ## Can be used as UBO
  BufferUsageStorageBufferBit = 32  ## Can be used as SSBO
  BufferUsageIndexBufferBit = 64  ## Can be used as source of fixed-function index fetch (index buffer)
  BufferUsageVertexBufferBit = 128  ## Can be used as source of fixed-function vertex fetch (VBO)
  BufferUsageIndirectBufferBit = 256  ## Can be the source of indirect parameters (e.g. indirect buffer, parameter buffer)

type VkBufferUsageFlagBits2KHR * = enum
  BufferUsage2TransferSrcBitKhr = 1
  BufferUsage2TransferDstBitKhr = 2
  BufferUsage2UniformTexelBufferBitKhr = 4
  BufferUsage2StorageTexelBufferBitKhr = 8
  BufferUsage2UniformBufferBitKhr = 16
  BufferUsage2StorageBufferBitKhr = 32
  BufferUsage2IndexBufferBitKhr = 64
  BufferUsage2VertexBufferBitKhr = 128
  BufferUsage2IndirectBufferBitKhr = 256

type VkBufferCreateFlagBits * = enum
  BufferCreateSparseBindingBit = 1  ## Buffer should support sparse backing
  BufferCreateSparseResidencyBit = 2  ## Buffer should support sparse backing with partial residency
  BufferCreateSparseAliasedBit = 4  ## Buffer should support constant data access to physical memory ranges mapped into multiple locations of sparse buffers

type VkShaderStageFlagBits * = enum
  ShaderStageVertexBit = 1
  ShaderStageTessellationControlBit = 2
  ShaderStageTessellationEvaluationBit = 4
  ShaderStageGeometryBit = 8
  ShaderStageFragmentBit = 16
  ShaderStageAllGraphics = 0x0000001F
  ShaderStageComputeBit = 32
  ShaderStageAll = 0x7FFFFFFF

type VkImageUsageFlagBits * = enum
  ImageUsageTransferSrcBit = 1  ## Can be used as a source of transfer operations
  ImageUsageTransferDstBit = 2  ## Can be used as a destination of transfer operations
  ImageUsageSampledBit = 4  ## Can be sampled from (SAMPLED_IMAGE and COMBINED_IMAGE_SAMPLER descriptor types)
  ImageUsageStorageBit = 8  ## Can be used as storage image (STORAGE_IMAGE descriptor type)
  ImageUsageColorAttachmentBit = 16  ## Can be used as framebuffer color attachment
  ImageUsageDepthStencilAttachmentBit = 32  ## Can be used as framebuffer depth/stencil attachment
  ImageUsageTransientAttachmentBit = 64  ## Image data not needed outside of rendering
  ImageUsageInputAttachmentBit = 128  ## Can be used as framebuffer input attachment

type VkImageCreateFlagBits * = enum
  ImageCreateSparseBindingBit = 1  ## Image should support sparse backing
  ImageCreateSparseResidencyBit = 2  ## Image should support sparse backing with partial residency
  ImageCreateSparseAliasedBit = 4  ## Image should support constant data access to physical memory ranges mapped into multiple locations of sparse images
  ImageCreateMutableFormatBit = 8  ## Allows image views to have different format than the base image
  ImageCreateCubeCompatibleBit = 16  ## Allows creating image views with cube type from the created image

type VkPipelineCreateFlagBits * = enum
  PipelineCreateDisableOptimizationBit = 1
  PipelineCreateAllowDerivativesBit = 2
  PipelineCreateDerivativeBit = 4

type VkPipelineCreateFlagBits2KHR * = enum
  PipelineCreate2DisableOptimizationBitKhr = 1
  PipelineCreate2AllowDerivativesBitKhr = 2
  PipelineCreate2DerivativeBitKhr = 4

type VkColorComponentFlagBits * = enum
  ColorComponentRBit = 1
  ColorComponentGBit = 2
  ColorComponentBBit = 4
  ColorComponentABit = 8

type VkFenceCreateFlagBits * = enum
  FenceCreateSignaledBit = 1

type VkFormatFeatureFlagBits * = enum
  FormatFeatureSampledImageBit = 1  ## Format can be used for sampled images (SAMPLED_IMAGE and COMBINED_IMAGE_SAMPLER descriptor types)
  FormatFeatureStorageImageBit = 2  ## Format can be used for storage images (STORAGE_IMAGE descriptor type)
  FormatFeatureStorageImageAtomicBit = 4  ## Format supports atomic operations in case it is used for storage images
  FormatFeatureUniformTexelBufferBit = 8  ## Format can be used for uniform texel buffers (TBOs)
  FormatFeatureStorageTexelBufferBit = 16  ## Format can be used for storage texel buffers (IBOs)
  FormatFeatureStorageTexelBufferAtomicBit = 32  ## Format supports atomic operations in case it is used for storage texel buffers
  FormatFeatureVertexBufferBit = 64  ## Format can be used for vertex buffers (VBOs)
  FormatFeatureColorAttachmentBit = 128  ## Format can be used for color attachment images
  FormatFeatureColorAttachmentBlendBit = 256  ## Format supports blending in case it is used for color attachment images
  FormatFeatureDepthStencilAttachmentBit = 512  ## Format can be used for depth/stencil attachment images
  FormatFeatureBlitSrcBit = 1024  ## Format can be used as the source image of blits with vkCmdBlitImage
  FormatFeatureBlitDstBit = 2048  ## Format can be used as the destination image of blits with vkCmdBlitImage
  FormatFeatureSampledImageFilterLinearBit = 4096  ## Format can be filtered with VK_FILTER_LINEAR when being sampled

type VkQueryControlFlagBits * = enum
  QueryControlPreciseBit = 1  ## Require precise results to be collected by the query

type VkQueryResultFlagBits * = enum
  QueryResult64Bit = 1  ## Results of the queries are written to the destination buffer as 64-bit values
  QueryResultWaitBit = 2  ## Results of the queries are waited on before proceeding with the result copy
  QueryResultWithAvailabilityBit = 4  ## Besides the results of the query, the availability of the results is also written
  QueryResultPartialBit = 8  ## Copy the partial results of the query even if the final results are not available

type VkCommandBufferUsageFlagBits * = enum
  CommandBufferUsageOneTimeSubmitBit = 1
  CommandBufferUsageRenderPassContinueBit = 2
  CommandBufferUsageSimultaneousUseBit = 4  ## Command buffer may be submitted/executed more than once simultaneously

type VkQueryPipelineStatisticFlagBits * = enum
  QueryPipelineStatisticInputAssemblyVerticesBit = 1  ## Optional
  QueryPipelineStatisticInputAssemblyPrimitivesBit = 2  ## Optional
  QueryPipelineStatisticVertexShaderInvocationsBit = 4  ## Optional
  QueryPipelineStatisticGeometryShaderInvocationsBit = 8  ## Optional
  QueryPipelineStatisticGeometryShaderPrimitivesBit = 16  ## Optional
  QueryPipelineStatisticClippingInvocationsBit = 32  ## Optional
  QueryPipelineStatisticClippingPrimitivesBit = 64  ## Optional
  QueryPipelineStatisticFragmentShaderInvocationsBit = 128  ## Optional
  QueryPipelineStatisticTessellationControlShaderPatchesBit = 256  ## Optional
  QueryPipelineStatisticTessellationEvaluationShaderInvocationsBit = 512  ## Optional
  QueryPipelineStatisticComputeShaderInvocationsBit = 1024  ## Optional

type VkImageAspectFlagBits * = enum
  ImageAspectColorBit = 1
  ImageAspectDepthBit = 2
  ImageAspectStencilBit = 4
  ImageAspectMetadataBit = 8

type VkSparseImageFormatFlagBits * = enum
  SparseImageFormatSingleMiptailBit = 1  ## Image uses a single mip tail region for all array layers
  SparseImageFormatAlignedMipSizeBit = 2  ## Image requires mip level dimensions to be an integer multiple of the sparse image block dimensions for non-tail mip levels.
  SparseImageFormatNonstandardBlockSizeBit = 4  ## Image uses a non-standard sparse image block dimensions

type VkSparseMemoryBindFlagBits * = enum
  SparseMemoryBindMetadataBit = 1  ## Operation binds resource metadata to memory

type VkPipelineStageFlagBits * = enum
  PipelineStageTopOfPipeBit = 1  ## Before subsequent commands are processed
  PipelineStageDrawIndirectBit = 2  ## Draw/DispatchIndirect command fetch
  PipelineStageVertexInputBit = 4  ## Vertex/index fetch
  PipelineStageVertexShaderBit = 8  ## Vertex shading
  PipelineStageTessellationControlShaderBit = 16  ## Tessellation control shading
  PipelineStageTessellationEvaluationShaderBit = 32  ## Tessellation evaluation shading
  PipelineStageGeometryShaderBit = 64  ## Geometry shading
  PipelineStageFragmentShaderBit = 128  ## Fragment shading
  PipelineStageEarlyFragmentTestsBit = 256  ## Early fragment (depth and stencil) tests
  PipelineStageLateFragmentTestsBit = 512  ## Late fragment (depth and stencil) tests
  PipelineStageColorAttachmentOutputBit = 1024  ## Color attachment writes
  PipelineStageComputeShaderBit = 2048  ## Compute shading
  PipelineStageTransferBit = 4096  ## Transfer/copy operations
  PipelineStageBottomOfPipeBit = 8192  ## After previous commands have completed
  PipelineStageHostBit = 16384  ## Indicates host (CPU) is a source/sink of the dependency
  PipelineStageAllGraphicsBit = 32768  ## All stages of the graphics pipeline
  PipelineStageAllCommandsBit = 65536  ## All stages supported on the queue

type VkCommandPoolCreateFlagBits * = enum
  CommandPoolCreateTransientBit = 1  ## Command buffers have a short lifetime
  CommandPoolCreateResetCommandBufferBit = 2  ## Command buffers may release their memory individually

type VkCommandPoolResetFlagBits * = enum
  CommandPoolResetReleaseResourcesBit = 1  ## Release resources owned by the pool

type VkCommandBufferResetFlagBits * = enum
  CommandBufferResetReleaseResourcesBit = 1  ## Release resources owned by the buffer

type VkSampleCountFlagBits * = enum
  SampleCount1Bit = 1  ## Sample count 1 supported
  SampleCount2Bit = 2  ## Sample count 2 supported
  SampleCount4Bit = 4  ## Sample count 4 supported
  SampleCount8Bit = 8  ## Sample count 8 supported
  SampleCount16Bit = 16  ## Sample count 16 supported
  SampleCount32Bit = 32  ## Sample count 32 supported
  SampleCount64Bit = 64  ## Sample count 64 supported

type VkAttachmentDescriptionFlagBits * = enum
  AttachmentDescriptionMayAliasBit = 1  ## The attachment may alias physical memory of another attachment in the same render pass

type VkStencilFaceFlagBits * = enum
  StencilFaceFrontBit = 1  ## Front face
  StencilFaceBackBit = 2  ## Back face
  StencilFaceFrontAndBack = 0x00000003  ## Front and back faces

type VkDescriptorPoolCreateFlagBits * = enum
  DescriptorPoolCreateFreeDescriptorSetBit = 1  ## Descriptor sets may be freed individually

type VkDependencyFlagBits * = enum
  DependencyByRegionBit = 1  ## Dependency is per pixel region

type VkSemaphoreWaitFlagBits * = enum
  SemaphoreWaitAnyBit = 1

type VkDisplayPlaneAlphaFlagBitsKHR * = enum
  DisplayPlaneAlphaOpaqueBitKhr = 1
  DisplayPlaneAlphaGlobalBitKhr = 2
  DisplayPlaneAlphaPerPixelBitKhr = 4
  DisplayPlaneAlphaPerPixelPremultipliedBitKhr = 8

type VkCompositeAlphaFlagBitsKHR * = enum
  CompositeAlphaOpaqueBitKhr = 1
  CompositeAlphaPreMultipliedBitKhr = 2
  CompositeAlphaPostMultipliedBitKhr = 4
  CompositeAlphaInheritBitKhr = 8

type VkSurfaceTransformFlagBitsKHR * = enum
  SurfaceTransformIdentityBitKhr = 1
  SurfaceTransformRotate90BitKhr = 2
  SurfaceTransformRotate180BitKhr = 4
  SurfaceTransformRotate270BitKhr = 8
  SurfaceTransformHorizontalMirrorBitKhr = 16
  SurfaceTransformHorizontalMirrorRotate90BitKhr = 32
  SurfaceTransformHorizontalMirrorRotate180BitKhr = 64
  SurfaceTransformHorizontalMirrorRotate270BitKhr = 128
  SurfaceTransformInheritBitKhr = 256

type VkSwapchainImageUsageFlagBitsANDROID * = enum
  SwapchainImageUsageSharedBitAndroid = 1

type VkDebugReportFlagBitsEXT * = enum
  DebugReportInformationBitExt = 1
  DebugReportWarningBitExt = 2
  DebugReportPerformanceWarningBitExt = 4
  DebugReportErrorBitExt = 8
  DebugReportDebugBitExt = 16

type VkExternalMemoryHandleTypeFlagBitsNV * = enum
  ExternalMemoryHandleTypeOpaqueWin32BitNv = 1
  ExternalMemoryHandleTypeOpaqueWin32KmtBitNv = 2
  ExternalMemoryHandleTypeD3d11ImageBitNv = 4
  ExternalMemoryHandleTypeD3d11ImageKmtBitNv = 8

type VkExternalMemoryFeatureFlagBitsNV * = enum
  ExternalMemoryFeatureDedicatedOnlyBitNv = 1
  ExternalMemoryFeatureExportableBitNv = 2
  ExternalMemoryFeatureImportableBitNv = 4

type VkSubgroupFeatureFlagBits * = enum
  SubgroupFeatureBasicBit = 1  ## Basic subgroup operations
  SubgroupFeatureVoteBit = 2  ## Vote subgroup operations
  SubgroupFeatureArithmeticBit = 4  ## Arithmetic subgroup operations
  SubgroupFeatureBallotBit = 8  ## Ballot subgroup operations
  SubgroupFeatureShuffleBit = 16  ## Shuffle subgroup operations
  SubgroupFeatureShuffleRelativeBit = 32  ## Shuffle relative subgroup operations
  SubgroupFeatureClusteredBit = 64  ## Clustered subgroup operations
  SubgroupFeatureQuadBit = 128  ## Quad subgroup operations

type VkIndirectCommandsLayoutUsageFlagBitsNV * = enum
  IndirectCommandsLayoutUsageExplicitPreprocessBitNv = 1
  IndirectCommandsLayoutUsageIndexedSequencesBitNv = 2
  IndirectCommandsLayoutUsageUnorderedSequencesBitNv = 4

type VkIndirectStateFlagBitsNV * = enum
  IndirectStateFlagFrontfaceBitNv = 1

type VkExternalMemoryHandleTypeFlagBits * = enum
  ExternalMemoryHandleTypeOpaqueFdBit = 1
  ExternalMemoryHandleTypeOpaqueWin32Bit = 2
  ExternalMemoryHandleTypeOpaqueWin32KmtBit = 4
  ExternalMemoryHandleTypeD3d11TextureBit = 8
  ExternalMemoryHandleTypeD3d11TextureKmtBit = 16
  ExternalMemoryHandleTypeD3d12HeapBit = 32
  ExternalMemoryHandleTypeD3d12ResourceBit = 64

type VkExternalMemoryFeatureFlagBits * = enum
  ExternalMemoryFeatureDedicatedOnlyBit = 1
  ExternalMemoryFeatureExportableBit = 2
  ExternalMemoryFeatureImportableBit = 4

type VkExternalSemaphoreHandleTypeFlagBits * = enum
  ExternalSemaphoreHandleTypeOpaqueFdBit = 1
  ExternalSemaphoreHandleTypeOpaqueWin32Bit = 2
  ExternalSemaphoreHandleTypeOpaqueWin32KmtBit = 4
  ExternalSemaphoreHandleTypeD3d12FenceBit = 8
  ExternalSemaphoreHandleTypeSyncFdBit = 16

type VkExternalSemaphoreFeatureFlagBits * = enum
  ExternalSemaphoreFeatureExportableBit = 1
  ExternalSemaphoreFeatureImportableBit = 2

type VkSemaphoreImportFlagBits * = enum
  SemaphoreImportTemporaryBit = 1

type VkExternalFenceHandleTypeFlagBits * = enum
  ExternalFenceHandleTypeOpaqueFdBit = 1
  ExternalFenceHandleTypeOpaqueWin32Bit = 2
  ExternalFenceHandleTypeOpaqueWin32KmtBit = 4
  ExternalFenceHandleTypeSyncFdBit = 8

type VkExternalFenceFeatureFlagBits * = enum
  ExternalFenceFeatureExportableBit = 1
  ExternalFenceFeatureImportableBit = 2

type VkFenceImportFlagBits * = enum
  FenceImportTemporaryBit = 1

type VkSurfaceCounterFlagBitsEXT * = enum
  SurfaceCounterVblankBitExt = 1

type VkPeerMemoryFeatureFlagBits * = enum
  PeerMemoryFeatureCopySrcBit = 1  ## Can read with vkCmdCopy commands
  PeerMemoryFeatureCopyDstBit = 2  ## Can write with vkCmdCopy commands
  PeerMemoryFeatureGenericSrcBit = 4  ## Can read with any access type/command
  PeerMemoryFeatureGenericDstBit = 8  ## Can write with and access type/command

type VkMemoryAllocateFlagBits * = enum
  MemoryAllocateDeviceMaskBit = 1  ## Force allocation on specific devices

type VkDeviceGroupPresentModeFlagBitsKHR * = enum
  DeviceGroupPresentModeLocalBitKhr = 1  ## Present from local memory
  DeviceGroupPresentModeRemoteBitKhr = 2  ## Present from remote memory
  DeviceGroupPresentModeSumBitKhr = 4  ## Present sum of local and/or remote memory
  DeviceGroupPresentModeLocalMultiDeviceBitKhr = 8  ## Each physical device presents from local memory

type VkDebugUtilsMessageSeverityFlagBitsEXT * = enum
  DebugUtilsMessageSeverityVerboseBitExt = 1
  DebugUtilsMessageSeverityInfoBitExt = 16
  DebugUtilsMessageSeverityWarningBitExt = 256
  DebugUtilsMessageSeverityErrorBitExt = 4096

type VkDebugUtilsMessageTypeFlagBitsEXT * = enum
  DebugUtilsMessageTypeGeneralBitExt = 1
  DebugUtilsMessageTypeValidationBitExt = 2
  DebugUtilsMessageTypePerformanceBitExt = 4

type VkDescriptorBindingFlagBits * = enum
  DescriptorBindingUpdateAfterBindBit = 1
  DescriptorBindingUpdateUnusedWhilePendingBit = 2
  DescriptorBindingPartiallyBoundBit = 4
  DescriptorBindingVariableDescriptorCountBit = 8

type VkConditionalRenderingFlagBitsEXT * = enum
  ConditionalRenderingInvertedBitExt = 1

type VkResolveModeFlagBits * = enum
  ResolveModeNone = 0
  ResolveModeSampleZeroBit = 1
  ResolveModeAverageBit = 2
  ResolveModeMinBit = 4
  ResolveModeMaxBit = 8

type VkGeometryInstanceFlagBitsKHR * = enum
  GeometryInstanceTriangleFacingCullDisableBitKhr = 1
  GeometryInstanceTriangleFlipFacingBitKhr = 2
  GeometryInstanceForceOpaqueBitKhr = 4
  GeometryInstanceForceNoOpaqueBitKhr = 8

type VkGeometryFlagBitsKHR * = enum
  GeometryOpaqueBitKhr = 1
  GeometryNoDuplicateAnyHitInvocationBitKhr = 2

type VkBuildAccelerationStructureFlagBitsKHR * = enum
  BuildAccelerationStructureAllowUpdateBitKhr = 1
  BuildAccelerationStructureAllowCompactionBitKhr = 2
  BuildAccelerationStructurePreferFastTraceBitKhr = 4
  BuildAccelerationStructurePreferFastBuildBitKhr = 8
  BuildAccelerationStructureLowMemoryBitKhr = 16

type VkAccelerationStructureCreateFlagBitsKHR * = enum
  AccelerationStructureCreateDeviceAddressCaptureReplayBitKhr = 1

type VkDeviceDiagnosticsConfigFlagBitsNV * = enum
  DeviceDiagnosticsConfigEnableShaderDebugInfoBitNv = 1
  DeviceDiagnosticsConfigEnableResourceTrackingBitNv = 2
  DeviceDiagnosticsConfigEnableAutomaticCheckpointsBitNv = 4
  DeviceDiagnosticsConfigEnableShaderErrorReportingBitNv = 8

type VkPipelineCreationFeedbackFlagBits * = enum
  PipelineCreationFeedbackValidBit = 1
  PipelineCreationFeedbackApplicationPipelineCacheHitBit = 2
  PipelineCreationFeedbackBasePipelineAccelerationBit = 4

type VkMemoryDecompressionMethodFlagBitsNV * = enum
  MemoryDecompressionMethodGdeflate10BitNv = 1

type VkPerformanceCounterDescriptionFlagBitsKHR * = enum
  PerformanceCounterDescriptionPerformanceImpactingBitKhr = 1
  PerformanceCounterDescriptionConcurrentlyImpactedBitKhr = 2

type VkToolPurposeFlagBits * = enum
  ToolPurposeValidationBit = 1
  ToolPurposeProfilingBit = 2
  ToolPurposeTracingBit = 4
  ToolPurposeAdditionalFeaturesBit = 8
  ToolPurposeModifyingFeaturesBit = 16

type VkAccessFlagBits2 * = enum
  Access2None = 0
  Access2IndirectCommandReadBit = 1
  Access2IndexReadBit = 2
  Access2VertexAttributeReadBit = 4
  Access2UniformReadBit = 8
  Access2InputAttachmentReadBit = 16
  Access2ShaderReadBit = 32
  Access2ShaderWriteBit = 64
  Access2ColorAttachmentReadBit = 128
  Access2ColorAttachmentWriteBit = 256
  Access2DepthStencilAttachmentReadBit = 512
  Access2DepthStencilAttachmentWriteBit = 1024
  Access2TransferReadBit = 2048
  Access2TransferWriteBit = 4096
  Access2HostReadBit = 8192
  Access2HostWriteBit = 16384
  Access2MemoryReadBit = 32768
  Access2MemoryWriteBit = 65536
  Access2ShaderSampledReadBit = 4294967296
  Access2ShaderStorageReadBit = 8589934592
  Access2ShaderStorageWriteBit = 17179869184

type VkPipelineStageFlagBits2 * = enum
  PipelineStage2None = 0
  PipelineStage2TopOfPipeBit = 1
  PipelineStage2DrawIndirectBit = 2
  PipelineStage2VertexInputBit = 4
  PipelineStage2VertexShaderBit = 8
  PipelineStage2TessellationControlShaderBit = 16
  PipelineStage2TessellationEvaluationShaderBit = 32
  PipelineStage2GeometryShaderBit = 64
  PipelineStage2FragmentShaderBit = 128
  PipelineStage2EarlyFragmentTestsBit = 256
  PipelineStage2LateFragmentTestsBit = 512
  PipelineStage2ColorAttachmentOutputBit = 1024
  PipelineStage2ComputeShaderBit = 2048
  PipelineStage2AllTransferBit = 4096
  PipelineStage2BottomOfPipeBit = 8192
  PipelineStage2HostBit = 16384
  PipelineStage2AllGraphicsBit = 32768
  PipelineStage2AllCommandsBit = 65536
  PipelineStage2CopyBit = 4294967296
  PipelineStage2ResolveBit = 8589934592
  PipelineStage2BlitBit = 17179869184
  PipelineStage2ClearBit = 34359738368
  PipelineStage2IndexInputBit = 68719476736
  PipelineStage2VertexAttributeInputBit = 137438953472
  PipelineStage2PreRasterizationShadersBit = 274877906944

type VkSubmitFlagBits * = enum
  SubmitProtectedBit = 1

type VkGraphicsPipelineLibraryFlagBitsEXT * = enum
  GraphicsPipelineLibraryVertexInputInterfaceBitExt = 1
  GraphicsPipelineLibraryPreRasterizationShadersBitExt = 2
  GraphicsPipelineLibraryFragmentShaderBitExt = 4
  GraphicsPipelineLibraryFragmentOutputInterfaceBitExt = 8

type VkDeviceAddressBindingFlagBitsEXT * = enum
  DeviceAddressBindingInternalObjectBitExt = 1

type VkFrameBoundaryFlagBitsEXT * = enum
  FrameBoundaryFrameEndBitExt = 1

type VkPresentScalingFlagBitsEXT * = enum
  PresentScalingOneToOneBitExt = 1
  PresentScalingAspectRatioStretchBitExt = 2
  PresentScalingStretchBitExt = 4

type VkPresentGravityFlagBitsEXT * = enum
  PresentGravityMinBitExt = 1
  PresentGravityMaxBitExt = 2
  PresentGravityCenteredBitExt = 4

type VkPhysicalDeviceSchedulingControlsFlagBitsARM * = enum
  PhysicalDeviceSchedulingControlsShaderCoreCountArm = 1

type VkVideoCodecOperationFlagBitsKHR * = enum
  VideoCodecOperationNoneKhr = 0

type VkVideoChromaSubsamplingFlagBitsKHR * = enum
  VideoChromaSubsamplingInvalidKhr = 0
  VideoChromaSubsamplingMonochromeBitKhr = 1
  VideoChromaSubsampling420BitKhr = 2
  VideoChromaSubsampling422BitKhr = 4
  VideoChromaSubsampling444BitKhr = 8

type VkVideoComponentBitDepthFlagBitsKHR * = enum
  VideoComponentBitDepthInvalidKhr = 0
  VideoComponentBitDepth8BitKhr = 1
  VideoComponentBitDepth10BitKhr = 4
  VideoComponentBitDepth12BitKhr = 16

type VkVideoCapabilityFlagBitsKHR * = enum
  VideoCapabilityProtectedContentBitKhr = 1
  VideoCapabilitySeparateReferenceImagesBitKhr = 2

type VkVideoSessionCreateFlagBitsKHR * = enum
  VideoSessionCreateProtectedContentBitKhr = 1

type VkVideoDecodeH264PictureLayoutFlagBitsKHR * = enum
  VideoDecodeH264PictureLayoutProgressiveKhr = 0
  VideoDecodeH264PictureLayoutInterlacedInterleavedLinesBitKhr = 1
  VideoDecodeH264PictureLayoutInterlacedSeparatePlanesBitKhr = 2

type VkVideoCodingControlFlagBitsKHR * = enum
  VideoCodingControlResetBitKhr = 1

type VkVideoDecodeUsageFlagBitsKHR * = enum
  VideoDecodeUsageDefaultKhr = 0
  VideoDecodeUsageTranscodingBitKhr = 1
  VideoDecodeUsageOfflineBitKhr = 2
  VideoDecodeUsageStreamingBitKhr = 4

type VkVideoDecodeCapabilityFlagBitsKHR * = enum
  VideoDecodeCapabilityDpbAndOutputCoincideBitKhr = 1
  VideoDecodeCapabilityDpbAndOutputDistinctBitKhr = 2

type VkVideoEncodeUsageFlagBitsKHR * = enum
  VideoEncodeUsageDefaultKhr = 0
  VideoEncodeUsageTranscodingBitKhr = 1
  VideoEncodeUsageStreamingBitKhr = 2
  VideoEncodeUsageRecordingBitKhr = 4
  VideoEncodeUsageConferencingBitKhr = 8

type VkVideoEncodeContentFlagBitsKHR * = enum
  VideoEncodeContentDefaultKhr = 0
  VideoEncodeContentCameraBitKhr = 1
  VideoEncodeContentDesktopBitKhr = 2
  VideoEncodeContentRenderedBitKhr = 4

type VkVideoEncodeCapabilityFlagBitsKHR * = enum
  VideoEncodeCapabilityPrecedingExternallyEncodedBytesBitKhr = 1
  VideoEncodeCapabilityInsufficientBitstreamBufferRangeDetectionBitKhr = 2

type VkVideoEncodeFeedbackFlagBitsKHR * = enum
  VideoEncodeFeedbackBitstreamBufferOffsetBitKhr = 1
  VideoEncodeFeedbackBitstreamBytesWrittenBitKhr = 2
  VideoEncodeFeedbackBitstreamHasOverridesBitKhr = 4

type VkVideoEncodeRateControlModeFlagBitsKHR * = enum
  VideoEncodeRateControlModeDefaultKhr = 0
  VideoEncodeRateControlModeDisabledBitKhr = 1
  VideoEncodeRateControlModeCbrBitKhr = 2
  VideoEncodeRateControlModeVbrBitKhr = 4

type VkVideoEncodeH264CapabilityFlagBitsKHR * = enum
  VideoEncodeH264CapabilityHrdComplianceBitKhr = 1
  VideoEncodeH264CapabilityPredictionWeightTableGeneratedBitKhr = 2
  VideoEncodeH264CapabilityRowUnalignedSliceBitKhr = 4
  VideoEncodeH264CapabilityDifferentSliceTypeBitKhr = 8
  VideoEncodeH264CapabilityBFrameInL0ListBitKhr = 16
  VideoEncodeH264CapabilityBFrameInL1ListBitKhr = 32
  VideoEncodeH264CapabilityPerPictureTypeMinMaxQpBitKhr = 64
  VideoEncodeH264CapabilityPerSliceConstantQpBitKhr = 128
  VideoEncodeH264CapabilityGeneratePrefixNaluBitKhr = 256

type VkVideoEncodeH264StdFlagBitsKHR * = enum
  VideoEncodeH264StdSeparateColorPlaneFlagSetBitKhr = 1
  VideoEncodeH264StdQpprimeYZeroTransformBypassFlagSetBitKhr = 2
  VideoEncodeH264StdScalingMatrixPresentFlagSetBitKhr = 4
  VideoEncodeH264StdChromaQpIndexOffsetBitKhr = 8
  VideoEncodeH264StdSecondChromaQpIndexOffsetBitKhr = 16
  VideoEncodeH264StdPicInitQpMinus26BitKhr = 32
  VideoEncodeH264StdWeightedPredFlagSetBitKhr = 64
  VideoEncodeH264StdWeightedBipredIdcExplicitBitKhr = 128
  VideoEncodeH264StdWeightedBipredIdcImplicitBitKhr = 256
  VideoEncodeH264StdTransform8x8ModeFlagSetBitKhr = 512
  VideoEncodeH264StdDirectSpatialMvPredFlagUnsetBitKhr = 1024
  VideoEncodeH264StdEntropyCodingModeFlagUnsetBitKhr = 2048
  VideoEncodeH264StdEntropyCodingModeFlagSetBitKhr = 4096
  VideoEncodeH264StdDirect8x8InferenceFlagUnsetBitKhr = 8192
  VideoEncodeH264StdConstrainedIntraPredFlagSetBitKhr = 16384
  VideoEncodeH264StdDeblockingFilterDisabledBitKhr = 32768
  VideoEncodeH264StdDeblockingFilterEnabledBitKhr = 65536
  VideoEncodeH264StdDeblockingFilterPartialBitKhr = 131072
  VideoEncodeH264StdSliceQpDeltaBitKhr = 524288
  VideoEncodeH264StdDifferentSliceQpDeltaBitKhr = 1048576

type VkVideoEncodeH264RateControlFlagBitsKHR * = enum
  VideoEncodeH264RateControlAttemptHrdComplianceBitKhr = 1
  VideoEncodeH264RateControlRegularGopBitKhr = 2
  VideoEncodeH264RateControlReferencePatternFlatBitKhr = 4
  VideoEncodeH264RateControlReferencePatternDyadicBitKhr = 8
  VideoEncodeH264RateControlTemporalLayerPatternDyadicBitKhr = 16

type VkHostImageCopyFlagBitsEXT * = enum
  HostImageCopyMemcpyExt = 1

type VkImageConstraintsInfoFlagBitsFUCHSIA * = enum
  ImageConstraintsInfoCpuReadRarelyFuchsia = 1
  ImageConstraintsInfoCpuReadOftenFuchsia = 2
  ImageConstraintsInfoCpuWriteRarelyFuchsia = 4
  ImageConstraintsInfoCpuWriteOftenFuchsia = 8
  ImageConstraintsInfoProtectedOptionalFuchsia = 16

type VkFormatFeatureFlagBits2 * = enum
  FormatFeature2SampledImageBit = 1
  FormatFeature2StorageImageBit = 2
  FormatFeature2StorageImageAtomicBit = 4
  FormatFeature2UniformTexelBufferBit = 8
  FormatFeature2StorageTexelBufferBit = 16
  FormatFeature2StorageTexelBufferAtomicBit = 32
  FormatFeature2VertexBufferBit = 64
  FormatFeature2ColorAttachmentBit = 128
  FormatFeature2ColorAttachmentBlendBit = 256
  FormatFeature2DepthStencilAttachmentBit = 512
  FormatFeature2BlitSrcBit = 1024
  FormatFeature2BlitDstBit = 2048
  FormatFeature2SampledImageFilterLinearBit = 4096
  FormatFeature2SampledImageFilterCubicBit = 8192
  FormatFeature2TransferSrcBit = 16384
  FormatFeature2TransferDstBit = 32768
  FormatFeature2SampledImageFilterMinmaxBit = 65536
  FormatFeature2MidpointChromaSamplesBit = 131072
  FormatFeature2SampledImageYcbcrConversionLinearFilterBit = 262144
  FormatFeature2SampledImageYcbcrConversionSeparateReconstructionFilterBit = 524288
  FormatFeature2SampledImageYcbcrConversionChromaReconstructionExplicitBit = 1048576
  FormatFeature2SampledImageYcbcrConversionChromaReconstructionExplicitForceableBit = 2097152
  FormatFeature2DisjointBit = 4194304
  FormatFeature2CositedChromaSamplesBit = 8388608
  FormatFeature2StorageReadWithoutFormatBit = 2147483648
  FormatFeature2StorageWriteWithoutFormatBit = 4294967296
  FormatFeature2SampledImageDepthComparisonBit = 8589934592

type VkRenderingFlagBits * = enum
  RenderingContentsSecondaryCommandBuffersBit = 1
  RenderingSuspendingBit = 2
  RenderingResumingBit = 4

type VkVideoEncodeH265CapabilityFlagBitsKHR * = enum
  VideoEncodeH265CapabilityHrdComplianceBitKhr = 1
  VideoEncodeH265CapabilityPredictionWeightTableGeneratedBitKhr = 2
  VideoEncodeH265CapabilityRowUnalignedSliceSegmentBitKhr = 4
  VideoEncodeH265CapabilityDifferentSliceSegmentTypeBitKhr = 8
  VideoEncodeH265CapabilityBFrameInL0ListBitKhr = 16
  VideoEncodeH265CapabilityBFrameInL1ListBitKhr = 32
  VideoEncodeH265CapabilityPerPictureTypeMinMaxQpBitKhr = 64
  VideoEncodeH265CapabilityPerSliceSegmentConstantQpBitKhr = 128
  VideoEncodeH265CapabilityMultipleTilesPerSliceSegmentBitKhr = 256
  VideoEncodeH265CapabilityMultipleSliceSegmentsPerTileBitKhr = 512

type VkVideoEncodeH265StdFlagBitsKHR * = enum
  VideoEncodeH265StdSeparateColorPlaneFlagSetBitKhr = 1
  VideoEncodeH265StdSampleAdaptiveOffsetEnabledFlagSetBitKhr = 2
  VideoEncodeH265StdScalingListDataPresentFlagSetBitKhr = 4
  VideoEncodeH265StdPcmEnabledFlagSetBitKhr = 8
  VideoEncodeH265StdSpsTemporalMvpEnabledFlagSetBitKhr = 16
  VideoEncodeH265StdInitQpMinus26BitKhr = 32
  VideoEncodeH265StdWeightedPredFlagSetBitKhr = 64
  VideoEncodeH265StdWeightedBipredFlagSetBitKhr = 128
  VideoEncodeH265StdLog2ParallelMergeLevelMinus2BitKhr = 256
  VideoEncodeH265StdSignDataHidingEnabledFlagSetBitKhr = 512
  VideoEncodeH265StdTransformSkipEnabledFlagSetBitKhr = 1024
  VideoEncodeH265StdTransformSkipEnabledFlagUnsetBitKhr = 2048
  VideoEncodeH265StdPpsSliceChromaQpOffsetsPresentFlagSetBitKhr = 4096
  VideoEncodeH265StdTransquantBypassEnabledFlagSetBitKhr = 8192
  VideoEncodeH265StdConstrainedIntraPredFlagSetBitKhr = 16384
  VideoEncodeH265StdEntropyCodingSyncEnabledFlagSetBitKhr = 32768
  VideoEncodeH265StdDeblockingFilterOverrideEnabledFlagSetBitKhr = 65536
  VideoEncodeH265StdDependentSliceSegmentsEnabledFlagSetBitKhr = 131072
  VideoEncodeH265StdDependentSliceSegmentFlagSetBitKhr = 262144
  VideoEncodeH265StdSliceQpDeltaBitKhr = 524288
  VideoEncodeH265StdDifferentSliceQpDeltaBitKhr = 1048576

type VkVideoEncodeH265RateControlFlagBitsKHR * = enum
  VideoEncodeH265RateControlAttemptHrdComplianceBitKhr = 1
  VideoEncodeH265RateControlRegularGopBitKhr = 2
  VideoEncodeH265RateControlReferencePatternFlatBitKhr = 4
  VideoEncodeH265RateControlReferencePatternDyadicBitKhr = 8
  VideoEncodeH265RateControlTemporalSubLayerPatternDyadicBitKhr = 16

type VkVideoEncodeH265CtbSizeFlagBitsKHR * = enum
  VideoEncodeH265CtbSize16BitKhr = 1
  VideoEncodeH265CtbSize32BitKhr = 2
  VideoEncodeH265CtbSize64BitKhr = 4

type VkVideoEncodeH265TransformBlockSizeFlagBitsKHR * = enum
  VideoEncodeH265TransformBlockSize4BitKhr = 1
  VideoEncodeH265TransformBlockSize8BitKhr = 2
  VideoEncodeH265TransformBlockSize16BitKhr = 4
  VideoEncodeH265TransformBlockSize32BitKhr = 8

type VkExportMetalObjectTypeFlagBitsEXT * = enum
  ExportMetalObjectTypeMetalDeviceBitExt = 1
  ExportMetalObjectTypeMetalCommandQueueBitExt = 2
  ExportMetalObjectTypeMetalBufferBitExt = 4
  ExportMetalObjectTypeMetalTextureBitExt = 8
  ExportMetalObjectTypeMetalIosurfaceBitExt = 16
  ExportMetalObjectTypeMetalSharedEventBitExt = 32

type VkImageCompressionFlagBitsEXT * = enum
  ImageCompressionDefaultExt = 0
  ImageCompressionFixedRateDefaultExt = 1
  ImageCompressionFixedRateExplicitExt = 2
  ImageCompressionDisabledExt = 4

type VkImageCompressionFixedRateFlagBitsEXT * = enum
  ImageCompressionFixedRateNoneExt = 0
  ImageCompressionFixedRate1bpcBitExt = 1
  ImageCompressionFixedRate2bpcBitExt = 2
  ImageCompressionFixedRate3bpcBitExt = 4
  ImageCompressionFixedRate4bpcBitExt = 8
  ImageCompressionFixedRate5bpcBitExt = 16
  ImageCompressionFixedRate6bpcBitExt = 32
  ImageCompressionFixedRate7bpcBitExt = 64
  ImageCompressionFixedRate8bpcBitExt = 128
  ImageCompressionFixedRate9bpcBitExt = 256
  ImageCompressionFixedRate10bpcBitExt = 512
  ImageCompressionFixedRate11bpcBitExt = 1024
  ImageCompressionFixedRate12bpcBitExt = 2048
  ImageCompressionFixedRate13bpcBitExt = 4096
  ImageCompressionFixedRate14bpcBitExt = 8192
  ImageCompressionFixedRate15bpcBitExt = 16384
  ImageCompressionFixedRate16bpcBitExt = 32768
  ImageCompressionFixedRate17bpcBitExt = 65536
  ImageCompressionFixedRate18bpcBitExt = 131072
  ImageCompressionFixedRate19bpcBitExt = 262144
  ImageCompressionFixedRate20bpcBitExt = 524288
  ImageCompressionFixedRate21bpcBitExt = 1048576
  ImageCompressionFixedRate22bpcBitExt = 2097152
  ImageCompressionFixedRate23bpcBitExt = 4194304
  ImageCompressionFixedRate24bpcBitExt = 8388608

type VkOpticalFlowGridSizeFlagBitsNV * = enum
  OpticalFlowGridSizeUnknownNv = 0
  OpticalFlowGridSize1x1BitNv = 1
  OpticalFlowGridSize2x2BitNv = 2
  OpticalFlowGridSize4x4BitNv = 4
  OpticalFlowGridSize8x8BitNv = 8

type VkOpticalFlowUsageFlagBitsNV * = enum
  OpticalFlowUsageUnknownNv = 0
  OpticalFlowUsageInputBitNv = 1
  OpticalFlowUsageOutputBitNv = 2
  OpticalFlowUsageHintBitNv = 4
  OpticalFlowUsageCostBitNv = 8
  OpticalFlowUsageGlobalFlowBitNv = 16

type VkOpticalFlowSessionCreateFlagBitsNV * = enum
  OpticalFlowSessionCreateEnableHintBitNv = 1
  OpticalFlowSessionCreateEnableCostBitNv = 2
  OpticalFlowSessionCreateEnableGlobalFlowBitNv = 4
  OpticalFlowSessionCreateAllowRegionsBitNv = 8
  OpticalFlowSessionCreateBothDirectionsBitNv = 16

type VkOpticalFlowExecuteFlagBitsNV * = enum
  OpticalFlowExecuteDisableTemporalHintsBitNv = 1

type VkBuildMicromapFlagBitsEXT * = enum
  BuildMicromapPreferFastTraceBitExt = 1
  BuildMicromapPreferFastBuildBitExt = 2
  BuildMicromapAllowCompactionBitExt = 4

type VkMicromapCreateFlagBitsEXT * = enum
  MicromapCreateDeviceAddressCaptureReplayBitExt = 1

type VkShaderCreateFlagBitsEXT * = enum
  ShaderCreateLinkStageBitExt = 1


