#[
=====================================

Types

=====================================
]#

# defines
template vkMakeVersion*(major, minor, patch: untyped): untyped =
  (((major) shl 22) or ((minor) shl 12) or (patch))
template vkVersionMajor*(version: untyped): untyped =
  ((uint32)(version) shr 22)
template vkVersionMajor*(version: untyped): untyped =
  ((uint32)(version) shr 22)
template vkVersionPatch*(version: untyped): untyped =
  ((uint32)(version) and 0x00000FFF)
template vkMakeApiVersion*(variant, major, minor, patch: untyped): untyped =
  (((variant) shl 29) or ((major) shl 22) or ((minor) shl 12) or (patch))
template vkApiVersionVariant*(version: untyped): untyped =
  ((uint32)(version) shr 29)
template vkApiVersionMajor*(version: untyped): untyped =
  (((uint32)(version) shr 22) and 0x000007FU)
template vkApiVersionMinor*(version: untyped): untyped =
  (((uint32)(version) shr 12) and 0x000003FF)
template vkApiVersionPatch*(version: untyped): untyped =
  ((uint32)(version) and 0x00000FFF)
const VKSC_API_VARIANT* = 1
const VK_API_VERSION* = vkMakeApiVersion(0, 1, 0, 0)
const VK_API_VERSION_1_0* = vkMakeApiVersion(0, 1, 0, 0)
const VK_API_VERSION_1_1* = vkMakeApiVersion(0, 1, 1, 0)
const VK_API_VERSION_1_2* = vkMakeApiVersion(0, 1, 2, 0)
const VK_API_VERSION_1_3* = vkMakeApiVersion(0, 1, 3, 0)
const VKSC_API_VERSION_1_0* = vkMakeApiVersion(VKSC_API_VARIANT, 1, 0, 0)
const VK_HEADER_VERSION* = 281
const VK_HEADER_VERSION_COMPLETE* = vkMakeApiVersion(0, 1, 3, VK_HEADER_VERSION)
const VK_NULL_HANDLE* = 0


# Base types


# Bitmasks
type VkFramebufferCreateFlags* = distinct VkFlags
type VkQueryPoolCreateFlags* = distinct VkFlags
type VkRenderPassCreateFlags* = distinct VkFlags
type VkSamplerCreateFlags* = distinct VkFlags
type VkPipelineLayoutCreateFlags* = distinct VkFlags
type VkPipelineCacheCreateFlags* = distinct VkFlags
type VkPipelineDepthStencilStateCreateFlags* = distinct VkFlags
type VkPipelineDynamicStateCreateFlags* = distinct VkFlags
type VkPipelineColorBlendStateCreateFlags* = distinct VkFlags
type VkPipelineMultisampleStateCreateFlags* = distinct VkFlags
type VkPipelineRasterizationStateCreateFlags* = distinct VkFlags
type VkPipelineViewportStateCreateFlags* = distinct VkFlags
type VkPipelineTessellationStateCreateFlags* = distinct VkFlags
type VkPipelineInputAssemblyStateCreateFlags* = distinct VkFlags
type VkPipelineVertexInputStateCreateFlags* = distinct VkFlags
type VkPipelineShaderStageCreateFlags* = distinct VkFlags
type VkDescriptorSetLayoutCreateFlags* = distinct VkFlags
type VkBufferViewCreateFlags* = distinct VkFlags
type VkInstanceCreateFlags* = distinct VkFlags
type VkDeviceCreateFlags* = distinct VkFlags
type VkDeviceQueueCreateFlags* = distinct VkFlags
type VkQueueFlags* = distinct VkFlags
type VkMemoryPropertyFlags* = distinct VkFlags
type VkMemoryHeapFlags* = distinct VkFlags
type VkAccessFlags* = distinct VkFlags
type VkBufferUsageFlags* = distinct VkFlags
type VkBufferCreateFlags* = distinct VkFlags
type VkShaderStageFlags* = distinct VkFlags
type VkImageUsageFlags* = distinct VkFlags
type VkImageCreateFlags* = distinct VkFlags
type VkImageViewCreateFlags* = distinct VkFlags
type VkPipelineCreateFlags* = distinct VkFlags
type VkColorComponentFlags* = distinct VkFlags
type VkFenceCreateFlags* = distinct VkFlags
type VkSemaphoreCreateFlags* = distinct VkFlags
type VkFormatFeatureFlags* = distinct VkFlags
type VkQueryControlFlags* = distinct VkFlags
type VkQueryResultFlags* = distinct VkFlags
type VkShaderModuleCreateFlags* = distinct VkFlags
type VkEventCreateFlags* = distinct VkFlags
type VkCommandPoolCreateFlags* = distinct VkFlags
type VkCommandPoolResetFlags* = distinct VkFlags
type VkCommandBufferResetFlags* = distinct VkFlags
type VkCommandBufferUsageFlags* = distinct VkFlags
type VkQueryPipelineStatisticFlags* = distinct VkFlags
type VkMemoryMapFlags* = distinct VkFlags
type VkMemoryUnmapFlagsKHR* = distinct VkFlags
type VkImageAspectFlags* = distinct VkFlags
type VkSparseMemoryBindFlags* = distinct VkFlags
type VkSparseImageFormatFlags* = distinct VkFlags
type VkSubpassDescriptionFlags* = distinct VkFlags
type VkPipelineStageFlags* = distinct VkFlags
type VkSampleCountFlags* = distinct VkFlags
type VkAttachmentDescriptionFlags* = distinct VkFlags
type VkStencilFaceFlags* = distinct VkFlags
type VkCullModeFlags* = distinct VkFlags
type VkDescriptorPoolCreateFlags* = distinct VkFlags
type VkDescriptorPoolResetFlags* = distinct VkFlags
type VkDependencyFlags* = distinct VkFlags
type VkSubgroupFeatureFlags* = distinct VkFlags
type VkIndirectCommandsLayoutUsageFlagsNV* = distinct VkFlags
type VkIndirectStateFlagsNV* = distinct VkFlags
type VkGeometryFlagsKHR* = distinct VkFlags
type VkGeometryFlagsNV* = VkGeometryFlagsKHR
type VkGeometryInstanceFlagsKHR* = distinct VkFlags
type VkGeometryInstanceFlagsNV* = VkGeometryInstanceFlagsKHR
type VkBuildAccelerationStructureFlagsKHR* = distinct VkFlags
type VkBuildAccelerationStructureFlagsNV* = VkBuildAccelerationStructureFlagsKHR
type VkPrivateDataSlotCreateFlags* = distinct VkFlags
type VkPrivateDataSlotCreateFlagsEXT* = VkPrivateDataSlotCreateFlags
type VkAccelerationStructureCreateFlagsKHR* = distinct VkFlags
type VkDescriptorUpdateTemplateCreateFlags* = distinct VkFlags
type VkDescriptorUpdateTemplateCreateFlagsKHR* = VkDescriptorUpdateTemplateCreateFlags
type VkPipelineCreationFeedbackFlags* = distinct VkFlags
type VkPipelineCreationFeedbackFlagsEXT* = VkPipelineCreationFeedbackFlags
type VkPerformanceCounterDescriptionFlagsKHR* = distinct VkFlags
type VkAcquireProfilingLockFlagsKHR* = distinct VkFlags
type VkSemaphoreWaitFlags* = distinct VkFlags
type VkSemaphoreWaitFlagsKHR* = VkSemaphoreWaitFlags
type VkPipelineCompilerControlFlagsAMD* = distinct VkFlags
type VkShaderCorePropertiesFlagsAMD* = distinct VkFlags
type VkDeviceDiagnosticsConfigFlagsNV* = distinct VkFlags
type VkRefreshObjectFlagsKHR* = distinct VkFlags
type VkAccessFlags2* = distinct VkFlags64
type VkAccessFlags2KHR* = VkAccessFlags2
type VkPipelineStageFlags2* = distinct VkFlags64
type VkPipelineStageFlags2KHR* = VkPipelineStageFlags2
type VkAccelerationStructureMotionInfoFlagsNV* = distinct VkFlags
type VkAccelerationStructureMotionInstanceFlagsNV* = distinct VkFlags
type VkFormatFeatureFlags2* = distinct VkFlags64
type VkFormatFeatureFlags2KHR* = VkFormatFeatureFlags2
type VkRenderingFlags* = distinct VkFlags
type VkMemoryDecompressionMethodFlagsNV* = distinct VkFlags64
type VkRenderingFlagsKHR* = VkRenderingFlags
type VkBuildMicromapFlagsEXT* = distinct VkFlags
type VkMicromapCreateFlagsEXT* = distinct VkFlags
type VkDirectDriverLoadingFlagsLUNARG* = distinct VkFlags
type VkPipelineCreateFlags2KHR* = distinct VkFlags64
type VkBufferUsageFlags2KHR* = distinct VkFlags64
type VkCompositeAlphaFlagsKHR* = distinct VkFlags
type VkDisplayPlaneAlphaFlagsKHR* = distinct VkFlags
type VkSurfaceTransformFlagsKHR* = distinct VkFlags
type VkSwapchainCreateFlagsKHR* = distinct VkFlags
type VkDisplayModeCreateFlagsKHR* = distinct VkFlags
type VkDisplaySurfaceCreateFlagsKHR* = distinct VkFlags
type VkAndroidSurfaceCreateFlagsKHR* = distinct VkFlags
type VkViSurfaceCreateFlagsNN* = distinct VkFlags
type VkWaylandSurfaceCreateFlagsKHR* = distinct VkFlags
type VkWin32SurfaceCreateFlagsKHR* = distinct VkFlags
type VkXlibSurfaceCreateFlagsKHR* = distinct VkFlags
type VkXcbSurfaceCreateFlagsKHR* = distinct VkFlags
type VkDirectFBSurfaceCreateFlagsEXT* = distinct VkFlags
type VkIOSSurfaceCreateFlagsMVK* = distinct VkFlags
type VkMacOSSurfaceCreateFlagsMVK* = distinct VkFlags
type VkMetalSurfaceCreateFlagsEXT* = distinct VkFlags
type VkImagePipeSurfaceCreateFlagsFUCHSIA* = distinct VkFlags
type VkStreamDescriptorSurfaceCreateFlagsGGP* = distinct VkFlags
type VkHeadlessSurfaceCreateFlagsEXT* = distinct VkFlags
type VkScreenSurfaceCreateFlagsQNX* = distinct VkFlags
type VkPeerMemoryFeatureFlags* = distinct VkFlags
type VkPeerMemoryFeatureFlagsKHR* = VkPeerMemoryFeatureFlags
type VkMemoryAllocateFlags* = distinct VkFlags
type VkMemoryAllocateFlagsKHR* = VkMemoryAllocateFlags
type VkDeviceGroupPresentModeFlagsKHR* = distinct VkFlags
type VkDebugReportFlagsEXT* = distinct VkFlags
type VkCommandPoolTrimFlags* = distinct VkFlags
type VkCommandPoolTrimFlagsKHR* = VkCommandPoolTrimFlags
type VkExternalMemoryHandleTypeFlagsNV* = distinct VkFlags
type VkExternalMemoryFeatureFlagsNV* = distinct VkFlags
type VkExternalMemoryHandleTypeFlags* = distinct VkFlags
type VkExternalMemoryHandleTypeFlagsKHR* = VkExternalMemoryHandleTypeFlags
type VkExternalMemoryFeatureFlags* = distinct VkFlags
type VkExternalMemoryFeatureFlagsKHR* = VkExternalMemoryFeatureFlags
type VkExternalSemaphoreHandleTypeFlags* = distinct VkFlags
type VkExternalSemaphoreHandleTypeFlagsKHR* = VkExternalSemaphoreHandleTypeFlags
type VkExternalSemaphoreFeatureFlags* = distinct VkFlags
type VkExternalSemaphoreFeatureFlagsKHR* = VkExternalSemaphoreFeatureFlags
type VkSemaphoreImportFlags* = distinct VkFlags
type VkSemaphoreImportFlagsKHR* = VkSemaphoreImportFlags
type VkExternalFenceHandleTypeFlags* = distinct VkFlags
type VkExternalFenceHandleTypeFlagsKHR* = VkExternalFenceHandleTypeFlags
type VkExternalFenceFeatureFlags* = distinct VkFlags
type VkExternalFenceFeatureFlagsKHR* = VkExternalFenceFeatureFlags
type VkFenceImportFlags* = distinct VkFlags
type VkFenceImportFlagsKHR* = VkFenceImportFlags
type VkSurfaceCounterFlagsEXT* = distinct VkFlags
type VkPipelineViewportSwizzleStateCreateFlagsNV* = distinct VkFlags
type VkPipelineDiscardRectangleStateCreateFlagsEXT* = distinct VkFlags
type VkPipelineCoverageToColorStateCreateFlagsNV* = distinct VkFlags
type VkPipelineCoverageModulationStateCreateFlagsNV* = distinct VkFlags
type VkPipelineCoverageReductionStateCreateFlagsNV* = distinct VkFlags
type VkValidationCacheCreateFlagsEXT* = distinct VkFlags
type VkDebugUtilsMessageSeverityFlagsEXT* = distinct VkFlags
type VkDebugUtilsMessageTypeFlagsEXT* = distinct VkFlags
type VkDebugUtilsMessengerCreateFlagsEXT* = distinct VkFlags
type VkDebugUtilsMessengerCallbackDataFlagsEXT* = distinct VkFlags
type VkDeviceMemoryReportFlagsEXT* = distinct VkFlags
type VkPipelineRasterizationConservativeStateCreateFlagsEXT* = distinct VkFlags
type VkDescriptorBindingFlags* = distinct VkFlags
type VkDescriptorBindingFlagsEXT* = VkDescriptorBindingFlags
type VkConditionalRenderingFlagsEXT* = distinct VkFlags
type VkResolveModeFlags* = distinct VkFlags
type VkResolveModeFlagsKHR* = VkResolveModeFlags
type VkPipelineRasterizationStateStreamCreateFlagsEXT* = distinct VkFlags
type VkPipelineRasterizationDepthClipStateCreateFlagsEXT* = distinct VkFlags
type VkSwapchainImageUsageFlagsANDROID* = distinct VkFlags
type VkToolPurposeFlags* = distinct VkFlags
type VkToolPurposeFlagsEXT* = VkToolPurposeFlags
type VkSubmitFlags* = distinct VkFlags
type VkSubmitFlagsKHR* = VkSubmitFlags
type VkImageFormatConstraintsFlagsFUCHSIA* = distinct VkFlags
type VkHostImageCopyFlagsEXT* = distinct VkFlags
type VkImageConstraintsInfoFlagsFUCHSIA* = distinct VkFlags
type VkGraphicsPipelineLibraryFlagsEXT* = distinct VkFlags
type VkImageCompressionFlagsEXT* = distinct VkFlags
type VkImageCompressionFixedRateFlagsEXT* = distinct VkFlags
type VkExportMetalObjectTypeFlagsEXT* = distinct VkFlags
type VkDeviceAddressBindingFlagsEXT* = distinct VkFlags
type VkOpticalFlowGridSizeFlagsNV* = distinct VkFlags
type VkOpticalFlowUsageFlagsNV* = distinct VkFlags
type VkOpticalFlowSessionCreateFlagsNV* = distinct VkFlags
type VkOpticalFlowExecuteFlagsNV* = distinct VkFlags
type VkFrameBoundaryFlagsEXT* = distinct VkFlags
type VkPresentScalingFlagsEXT* = distinct VkFlags
type VkPresentGravityFlagsEXT* = distinct VkFlags
type VkShaderCreateFlagsEXT* = distinct VkFlags
type VkPhysicalDeviceSchedulingControlsFlagsARM* = distinct VkFlags64
type VkVideoCodecOperationFlagsKHR* = distinct VkFlags
type VkVideoCapabilityFlagsKHR* = distinct VkFlags
type VkVideoSessionCreateFlagsKHR* = distinct VkFlags
type VkVideoSessionParametersCreateFlagsKHR* = distinct VkFlags
type VkVideoBeginCodingFlagsKHR* = distinct VkFlags
type VkVideoEndCodingFlagsKHR* = distinct VkFlags
type VkVideoCodingControlFlagsKHR* = distinct VkFlags
type VkVideoDecodeUsageFlagsKHR* = distinct VkFlags
type VkVideoDecodeCapabilityFlagsKHR* = distinct VkFlags
type VkVideoDecodeFlagsKHR* = distinct VkFlags
type VkVideoDecodeH264PictureLayoutFlagsKHR* = distinct VkFlags
type VkVideoEncodeFlagsKHR* = distinct VkFlags
type VkVideoEncodeUsageFlagsKHR* = distinct VkFlags
type VkVideoEncodeContentFlagsKHR* = distinct VkFlags
type VkVideoEncodeCapabilityFlagsKHR* = distinct VkFlags
type VkVideoEncodeFeedbackFlagsKHR* = distinct VkFlags
type VkVideoEncodeRateControlFlagsKHR* = distinct VkFlags
type VkVideoEncodeRateControlModeFlagsKHR* = distinct VkFlags
type VkVideoChromaSubsamplingFlagsKHR* = distinct VkFlags
type VkVideoComponentBitDepthFlagsKHR* = distinct VkFlags
type VkVideoEncodeH264CapabilityFlagsKHR* = distinct VkFlags
type VkVideoEncodeH264StdFlagsKHR* = distinct VkFlags
type VkVideoEncodeH264RateControlFlagsKHR* = distinct VkFlags
type VkVideoEncodeH265CapabilityFlagsKHR* = distinct VkFlags
type VkVideoEncodeH265StdFlagsKHR* = distinct VkFlags
type VkVideoEncodeH265RateControlFlagsKHR* = distinct VkFlags
type VkVideoEncodeH265CtbSizeFlagsKHR* = distinct VkFlags
type VkVideoEncodeH265TransformBlockSizeFlagsKHR* = distinct VkFlags

