{.experimental: "codeReordering".}
# AutoGenerated File
# TODO: Add VulkanNim Header here
import ./vulkan_consts
import ./vulkan_enums
import ./vulkan_types
import ./vulkan_handles
import ./vulkan_funcpointers

## Vulkan Structs
type VkBaseOutStructure* = object
  sType*: VkStructureType
  pNext*: ptr VkBaseOutStructure


type VkBaseInStructure* = object
  sType*: VkStructureType
  pNext*: ptr VkBaseInStructure


type VkOffset2D* = object
  x*: int32
  y*: int32


type VkOffset3D* = object
  x*: int32
  y*: int32
  z*: int32


type VkExtent2D* = object
  width*: uint32
  height*: uint32


type VkExtent3D* = object
  width*: uint32
  height*: uint32
  depth*: uint32


type VkViewport* = object
  x*: float32
  y*: float32
  width*: float32
  height*: float32
  minDepth*: float32
  maxDepth*: float32


type VkRect2D* = object
  offset*: VkOffset2D
  extent*: VkExtent2D


type VkClearRect* = object
  rect*: VkRect2D
  baseArrayLayer*: uint32
  layerCount*: uint32


type VkComponentMapping* = object
  r*: VkComponentSwizzle
  g*: VkComponentSwizzle
  b*: VkComponentSwizzle
  a*: VkComponentSwizzle


type VkPhysicalDeviceProperties* = object
  apiVersion*: uint32
  driverVersion*: uint32
  vendorID*: uint32
  deviceID*: uint32
  deviceType*: VkPhysicalDeviceType
  deviceName*: array[VK_MAX_PHYSICAL_DEVICE_NAME_SIZE, char]
  pipelineCacheUUID*: array[VK_UUID_SIZE, uint8]
  limits*: VkPhysicalDeviceLimits
  sparseProperties*: VkPhysicalDeviceSparseProperties


type VkExtensionProperties* = object
  extensionName*: array[VK_MAX_EXTENSION_NAME_SIZE, char]
  specVersion*: uint32


type VkLayerProperties* = object
  layerName*: array[VK_MAX_EXTENSION_NAME_SIZE, char]
  specVersion*: uint32
  implementationVersion*: uint32
  description*: array[VK_MAX_DESCRIPTION_SIZE, char]


type VkApplicationInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  pApplicationName*: ptr char
  applicationVersion*: uint32
  pEngineName*: ptr char
  engineVersion*: uint32
  apiVersion*: uint32


type VkAllocationCallbacks* = object
  pUserData*: pointer
  pfnAllocation*: PFN_vkAllocationFunction
  pfnReallocation*: PFN_vkReallocationFunction
  pfnFree*: PFN_vkFreeFunction
  pfnInternalAllocation*: PFN_vkInternalAllocationNotification
  pfnInternalFree*: PFN_vkInternalFreeNotification


type VkDeviceQueueCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkDeviceQueueCreateFlags
  queueFamilyIndex*: uint32
  queueCount*: uint32
  pQueuePriorities*: ptr float32


type VkDeviceCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkDeviceCreateFlags
  queueCreateInfoCount*: uint32
  pQueueCreateInfos*: ptr VkDeviceQueueCreateInfo
  enabledLayerCount*: uint32
  ppEnabledLayerNames*: ptr ptr char
  enabledExtensionCount*: uint32
  ppEnabledExtensionNames*: ptr ptr char
  pEnabledFeatures*: ptr VkPhysicalDeviceFeatures


type VkInstanceCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkInstanceCreateFlags
  pApplicationInfo*: ptr VkApplicationInfo
  enabledLayerCount*: uint32
  ppEnabledLayerNames*: ptr ptr char
  enabledExtensionCount*: uint32
  ppEnabledExtensionNames*: ptr ptr char


type VkQueueFamilyProperties* = object
  queueFlags*: VkQueueFlags
  queueCount*: uint32
  timestampValidBits*: uint32
  minImageTransferGranularity*: VkExtent3D


type VkPhysicalDeviceMemoryProperties* = object
  memoryTypeCount*: uint32
  memoryTypes*: array[VK_MAX_MEMORY_TYPES, VkMemoryType]
  memoryHeapCount*: uint32
  memoryHeaps*: array[VK_MAX_MEMORY_HEAPS, VkMemoryHeap]


type VkMemoryAllocateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  allocationSize*: VkDeviceSize
  memoryTypeIndex*: uint32


type VkMemoryRequirements* = object
  size*: VkDeviceSize
  alignment*: VkDeviceSize
  memoryTypeBits*: uint32


type VkSparseImageFormatProperties* = object
  aspectMask*: VkImageAspectFlags
  imageGranularity*: VkExtent3D
  flags*: VkSparseImageFormatFlags


type VkSparseImageMemoryRequirements* = object
  formatProperties*: VkSparseImageFormatProperties
  imageMipTailFirstLod*: uint32
  imageMipTailSize*: VkDeviceSize
  imageMipTailOffset*: VkDeviceSize
  imageMipTailStride*: VkDeviceSize


type VkMemoryType* = object
  propertyFlags*: VkMemoryPropertyFlags
  heapIndex*: uint32


type VkMemoryHeap* = object
  size*: VkDeviceSize
  flags*: VkMemoryHeapFlags


type VkMappedMemoryRange* = object
  sType*: VkStructureType
  pNext*: pointer
  memory*: VkDeviceMemory
  offset*: VkDeviceSize
  size*: VkDeviceSize


type VkFormatProperties* = object
  linearTilingFeatures*: VkFormatFeatureFlags
  optimalTilingFeatures*: VkFormatFeatureFlags
  bufferFeatures*: VkFormatFeatureFlags


type VkImageFormatProperties* = object
  maxExtent*: VkExtent3D
  maxMipLevels*: uint32
  maxArrayLayers*: uint32
  sampleCounts*: VkSampleCountFlags
  maxResourceSize*: VkDeviceSize


type VkDescriptorBufferInfo* = object
  buffer*: VkBuffer
  offset*: VkDeviceSize
  range*: VkDeviceSize


type VkDescriptorImageInfo* = object
  sampler*: VkSampler
  imageView*: VkImageView
  imageLayout*: VkImageLayout


type VkWriteDescriptorSet* = object
  sType*: VkStructureType
  pNext*: pointer
  dstSet*: VkDescriptorSet
  dstBinding*: uint32
  dstArrayElement*: uint32
  descriptorCount*: uint32
  descriptorType*: VkDescriptorType
  pImageInfo*: ptr VkDescriptorImageInfo
  pBufferInfo*: ptr VkDescriptorBufferInfo
  pTexelBufferView*: ptr VkBufferView


type VkCopyDescriptorSet* = object
  sType*: VkStructureType
  pNext*: pointer
  srcSet*: VkDescriptorSet
  srcBinding*: uint32
  srcArrayElement*: uint32
  dstSet*: VkDescriptorSet
  dstBinding*: uint32
  dstArrayElement*: uint32
  descriptorCount*: uint32


type VkBufferCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkBufferCreateFlags
  size*: VkDeviceSize
  usage*: VkBufferUsageFlags
  sharingMode*: VkSharingMode
  queueFamilyIndexCount*: uint32
  pQueueFamilyIndices*: ptr uint32


type VkBufferViewCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkBufferViewCreateFlags
  buffer*: VkBuffer
  format*: VkFormat
  offset*: VkDeviceSize
  range*: VkDeviceSize


type VkImageSubresource* = object
  aspectMask*: VkImageAspectFlags
  mipLevel*: uint32
  arrayLayer*: uint32


type VkImageSubresourceLayers* = object
  aspectMask*: VkImageAspectFlags
  mipLevel*: uint32
  baseArrayLayer*: uint32
  layerCount*: uint32


type VkImageSubresourceRange* = object
  aspectMask*: VkImageAspectFlags
  baseMipLevel*: uint32
  levelCount*: uint32
  baseArrayLayer*: uint32
  layerCount*: uint32


type VkMemoryBarrier* = object
  sType*: VkStructureType
  pNext*: pointer
  srcAccessMask*: VkAccessFlags
  dstAccessMask*: VkAccessFlags


type VkBufferMemoryBarrier* = object
  sType*: VkStructureType
  pNext*: pointer
  srcAccessMask*: VkAccessFlags
  dstAccessMask*: VkAccessFlags
  srcQueueFamilyIndex*: uint32
  dstQueueFamilyIndex*: uint32
  buffer*: VkBuffer
  offset*: VkDeviceSize
  size*: VkDeviceSize


type VkImageMemoryBarrier* = object
  sType*: VkStructureType
  pNext*: pointer
  srcAccessMask*: VkAccessFlags
  dstAccessMask*: VkAccessFlags
  oldLayout*: VkImageLayout
  newLayout*: VkImageLayout
  srcQueueFamilyIndex*: uint32
  dstQueueFamilyIndex*: uint32
  image*: VkImage
  subresourceRange*: VkImageSubresourceRange


type VkImageCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkImageCreateFlags
  imageType*: VkImageType
  format*: VkFormat
  extent*: VkExtent3D
  mipLevels*: uint32
  arrayLayers*: uint32
  samples*: VkSampleCountFlagBits
  tiling*: VkImageTiling
  usage*: VkImageUsageFlags
  sharingMode*: VkSharingMode
  queueFamilyIndexCount*: uint32
  pQueueFamilyIndices*: ptr uint32
  initialLayout*: VkImageLayout


type VkSubresourceLayout* = object
  offset*: VkDeviceSize
  size*: VkDeviceSize
  rowPitch*: VkDeviceSize
  arrayPitch*: VkDeviceSize
  depthPitch*: VkDeviceSize


type VkImageViewCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkImageViewCreateFlags
  image*: VkImage
  viewType*: VkImageViewType
  format*: VkFormat
  components*: VkComponentMapping
  subresourceRange*: VkImageSubresourceRange


type VkBufferCopy* = object
  srcOffset*: VkDeviceSize
  dstOffset*: VkDeviceSize
  size*: VkDeviceSize


type VkSparseMemoryBind* = object
  resourceOffset*: VkDeviceSize
  size*: VkDeviceSize
  memory*: VkDeviceMemory
  memoryOffset*: VkDeviceSize
  flags*: VkSparseMemoryBindFlags


type VkSparseImageMemoryBind* = object
  subresource*: VkImageSubresource
  offset*: VkOffset3D
  extent*: VkExtent3D
  memory*: VkDeviceMemory
  memoryOffset*: VkDeviceSize
  flags*: VkSparseMemoryBindFlags


type VkSparseBufferMemoryBindInfo* = object
  buffer*: VkBuffer
  bindCount*: uint32
  pBinds*: ptr VkSparseMemoryBind


type VkSparseImageOpaqueMemoryBindInfo* = object
  image*: VkImage
  bindCount*: uint32
  pBinds*: ptr VkSparseMemoryBind


type VkSparseImageMemoryBindInfo* = object
  image*: VkImage
  bindCount*: uint32
  pBinds*: ptr VkSparseImageMemoryBind


type VkBindSparseInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  waitSemaphoreCount*: uint32
  pWaitSemaphores*: ptr VkSemaphore
  bufferBindCount*: uint32
  pBufferBinds*: ptr VkSparseBufferMemoryBindInfo
  imageOpaqueBindCount*: uint32
  pImageOpaqueBinds*: ptr VkSparseImageOpaqueMemoryBindInfo
  imageBindCount*: uint32
  pImageBinds*: ptr VkSparseImageMemoryBindInfo
  signalSemaphoreCount*: uint32
  pSignalSemaphores*: ptr VkSemaphore


type VkImageCopy* = object
  srcSubresource*: VkImageSubresourceLayers
  srcOffset*: VkOffset3D
  dstSubresource*: VkImageSubresourceLayers
  dstOffset*: VkOffset3D
  extent*: VkExtent3D


type VkImageBlit* = object
  srcSubresource*: VkImageSubresourceLayers
  srcOffsets*: array[2, VkOffset3D]
  dstSubresource*: VkImageSubresourceLayers
  dstOffsets*: array[2, VkOffset3D]


type VkBufferImageCopy* = object
  bufferOffset*: VkDeviceSize
  bufferRowLength*: uint32
  bufferImageHeight*: uint32
  imageSubresource*: VkImageSubresourceLayers
  imageOffset*: VkOffset3D
  imageExtent*: VkExtent3D


type VkImageResolve* = object
  srcSubresource*: VkImageSubresourceLayers
  srcOffset*: VkOffset3D
  dstSubresource*: VkImageSubresourceLayers
  dstOffset*: VkOffset3D
  extent*: VkExtent3D


type VkShaderModuleCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkShaderModuleCreateFlags
  codeSize*: csize_t
  pCode*: ptr uint32


type VkDescriptorSetLayoutBinding* = object
  binding*: uint32
  descriptorType*: VkDescriptorType
  descriptorCount*: uint32
  stageFlags*: VkShaderStageFlags
  pImmutableSamplers*: ptr VkSampler


type VkDescriptorSetLayoutCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkDescriptorSetLayoutCreateFlags
  bindingCount*: uint32
  pBindings*: ptr VkDescriptorSetLayoutBinding


type VkDescriptorPoolSize* = object
  `type`*: VkDescriptorType
  descriptorCount*: uint32


type VkDescriptorPoolCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkDescriptorPoolCreateFlags
  maxSets*: uint32
  poolSizeCount*: uint32
  pPoolSizes*: ptr VkDescriptorPoolSize


type VkDescriptorSetAllocateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  descriptorPool*: VkDescriptorPool
  descriptorSetCount*: uint32
  pSetLayouts*: ptr VkDescriptorSetLayout


type VkSpecializationMapEntry* = object
  constantID*: uint32
  offset*: uint32
  size*: csize_t


type VkSpecializationInfo* = object
  mapEntryCount*: uint32
  pMapEntries*: ptr VkSpecializationMapEntry
  dataSize*: csize_t
  pData*: pointer


type VkPipelineShaderStageCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineShaderStageCreateFlags
  stage*: VkShaderStageFlagBits
  module*: VkShaderModule
  pName*: ptr char
  pSpecializationInfo*: ptr VkSpecializationInfo


type VkComputePipelineCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineCreateFlags
  stage*: VkPipelineShaderStageCreateInfo
  layout*: VkPipelineLayout
  basePipelineHandle*: VkPipeline
  basePipelineIndex*: int32


type VkVertexInputBindingDescription* = object
  binding*: uint32
  stride*: uint32
  inputRate*: VkVertexInputRate


type VkVertexInputAttributeDescription* = object
  location*: uint32
  binding*: uint32
  format*: VkFormat
  offset*: uint32


type VkPipelineVertexInputStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineVertexInputStateCreateFlags
  vertexBindingDescriptionCount*: uint32
  pVertexBindingDescriptions*: ptr VkVertexInputBindingDescription
  vertexAttributeDescriptionCount*: uint32
  pVertexAttributeDescriptions*: ptr VkVertexInputAttributeDescription


type VkPipelineInputAssemblyStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineInputAssemblyStateCreateFlags
  topology*: VkPrimitiveTopology
  primitiveRestartEnable*: VkBool32


type VkPipelineTessellationStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineTessellationStateCreateFlags
  patchControlPoints*: uint32


type VkPipelineViewportStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineViewportStateCreateFlags
  viewportCount*: uint32
  pViewports*: ptr VkViewport
  scissorCount*: uint32
  pScissors*: ptr VkRect2D


type VkPipelineRasterizationStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineRasterizationStateCreateFlags
  depthClampEnable*: VkBool32
  rasterizerDiscardEnable*: VkBool32
  polygonMode*: VkPolygonMode
  cullMode*: VkCullModeFlags
  frontFace*: VkFrontFace
  depthBiasEnable*: VkBool32
  depthBiasConstantFactor*: float32
  depthBiasClamp*: float32
  depthBiasSlopeFactor*: float32
  lineWidth*: float32


type VkPipelineMultisampleStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineMultisampleStateCreateFlags
  rasterizationSamples*: VkSampleCountFlagBits
  sampleShadingEnable*: VkBool32
  minSampleShading*: float32
  pSampleMask*: ptr VkSampleMask
  alphaToCoverageEnable*: VkBool32
  alphaToOneEnable*: VkBool32


type VkPipelineColorBlendAttachmentState* = object
  blendEnable*: VkBool32
  srcColorBlendFactor*: VkBlendFactor
  dstColorBlendFactor*: VkBlendFactor
  colorBlendOp*: VkBlendOp
  srcAlphaBlendFactor*: VkBlendFactor
  dstAlphaBlendFactor*: VkBlendFactor
  alphaBlendOp*: VkBlendOp
  colorWriteMask*: VkColorComponentFlags


type VkPipelineColorBlendStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineColorBlendStateCreateFlags
  logicOpEnable*: VkBool32
  logicOp*: VkLogicOp
  attachmentCount*: uint32
  pAttachments*: ptr VkPipelineColorBlendAttachmentState
  blendConstants*: array[4, float32]


type VkPipelineDynamicStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineDynamicStateCreateFlags
  dynamicStateCount*: uint32
  pDynamicStates*: ptr VkDynamicState


type VkStencilOpState* = object
  failOp*: VkStencilOp
  passOp*: VkStencilOp
  depthFailOp*: VkStencilOp
  compareOp*: VkCompareOp
  compareMask*: uint32
  writeMask*: uint32
  reference*: uint32


type VkPipelineDepthStencilStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineDepthStencilStateCreateFlags
  depthTestEnable*: VkBool32
  depthWriteEnable*: VkBool32
  depthCompareOp*: VkCompareOp
  depthBoundsTestEnable*: VkBool32
  stencilTestEnable*: VkBool32
  front*: VkStencilOpState
  back*: VkStencilOpState
  minDepthBounds*: float32
  maxDepthBounds*: float32


type VkGraphicsPipelineCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineCreateFlags
  stageCount*: uint32
  pStages*: ptr VkPipelineShaderStageCreateInfo
  pVertexInputState*: ptr VkPipelineVertexInputStateCreateInfo
  pInputAssemblyState*: ptr VkPipelineInputAssemblyStateCreateInfo
  pTessellationState*: ptr VkPipelineTessellationStateCreateInfo
  pViewportState*: ptr VkPipelineViewportStateCreateInfo
  pRasterizationState*: ptr VkPipelineRasterizationStateCreateInfo
  pMultisampleState*: ptr VkPipelineMultisampleStateCreateInfo
  pDepthStencilState*: ptr VkPipelineDepthStencilStateCreateInfo
  pColorBlendState*: ptr VkPipelineColorBlendStateCreateInfo
  pDynamicState*: ptr VkPipelineDynamicStateCreateInfo
  layout*: VkPipelineLayout
  renderPass*: VkRenderPass
  subpass*: uint32
  basePipelineHandle*: VkPipeline
  basePipelineIndex*: int32


type VkPipelineCacheCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineCacheCreateFlags
  initialDataSize*: csize_t
  pInitialData*: pointer


type VkPipelineCacheHeaderVersionOne* = object
  headerSize*: uint32
  headerVersion*: VkPipelineCacheHeaderVersion
  vendorID*: uint32
  deviceID*: uint32
  pipelineCacheUUID*: array[VK_UUID_SIZE, uint8]


type VkPipelineCacheStageValidationIndexEntry* = object
  codeSize*: uint64
  codeOffset*: uint64


type VkPipelineCacheSafetyCriticalIndexEntry* = object
  pipelineIdentifier*: array[VK_UUID_SIZE, uint8]
  pipelineMemorySize*: uint64
  jsonSize*: uint64
  jsonOffset*: uint64
  stageIndexCount*: uint32
  stageIndexStride*: uint32
  stageIndexOffset*: uint64


type VkPipelineCacheHeaderVersionSafetyCriticalOne* = object
  headerVersionOne*: VkPipelineCacheHeaderVersionOne
  validationVersion*: VkPipelineCacheValidationVersion
  implementationData*: uint32
  pipelineIndexCount*: uint32
  pipelineIndexStride*: uint32
  pipelineIndexOffset*: uint64


type VkPushConstantRange* = object
  stageFlags*: VkShaderStageFlags
  offset*: uint32
  size*: uint32


type VkPipelineLayoutCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPipelineLayoutCreateFlags
  setLayoutCount*: uint32
  pSetLayouts*: ptr VkDescriptorSetLayout
  pushConstantRangeCount*: uint32
  pPushConstantRanges*: ptr VkPushConstantRange


type VkSamplerCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkSamplerCreateFlags
  magFilter*: VkFilter
  minFilter*: VkFilter
  mipmapMode*: VkSamplerMipmapMode
  addressModeU*: VkSamplerAddressMode
  addressModeV*: VkSamplerAddressMode
  addressModeW*: VkSamplerAddressMode
  mipLodBias*: float32
  anisotropyEnable*: VkBool32
  maxAnisotropy*: float32
  compareEnable*: VkBool32
  compareOp*: VkCompareOp
  minLod*: float32
  maxLod*: float32
  borderColor*: VkBorderColor
  unnormalizedCoordinates*: VkBool32


type VkCommandPoolCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkCommandPoolCreateFlags
  queueFamilyIndex*: uint32


type VkCommandBufferAllocateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  commandPool*: VkCommandPool
  level*: VkCommandBufferLevel
  commandBufferCount*: uint32


type VkCommandBufferInheritanceInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  renderPass*: VkRenderPass
  subpass*: uint32
  framebuffer*: VkFramebuffer
  occlusionQueryEnable*: VkBool32
  queryFlags*: VkQueryControlFlags
  pipelineStatistics*: VkQueryPipelineStatisticFlags


type VkCommandBufferBeginInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkCommandBufferUsageFlags
  pInheritanceInfo*: ptr VkCommandBufferInheritanceInfo


type VkRenderPassBeginInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  renderPass*: VkRenderPass
  framebuffer*: VkFramebuffer
  renderArea*: VkRect2D
  clearValueCount*: uint32
  pClearValues*: ptr VkClearValue


type VkClearColorValue* {.union.} = object
  float32*: array[4, float32]
  int32*: array[4, int32]
  uint32*: array[4, uint32]


type VkClearDepthStencilValue* = object
  depth*: float32
  stencil*: uint32


type VkClearValue* {.union.} = object
  color*: VkClearColorValue
  depthStencil*: VkClearDepthStencilValue


type VkClearAttachment* = object
  aspectMask*: VkImageAspectFlags
  colorAttachment*: uint32
  clearValue*: VkClearValue


type VkAttachmentDescription* = object
  flags*: VkAttachmentDescriptionFlags
  format*: VkFormat
  samples*: VkSampleCountFlagBits
  loadOp*: VkAttachmentLoadOp
  storeOp*: VkAttachmentStoreOp
  stencilLoadOp*: VkAttachmentLoadOp
  stencilStoreOp*: VkAttachmentStoreOp
  initialLayout*: VkImageLayout
  finalLayout*: VkImageLayout


type VkAttachmentReference* = object
  attachment*: uint32
  layout*: VkImageLayout


type VkSubpassDescription* = object
  flags*: VkSubpassDescriptionFlags
  pipelineBindPoint*: VkPipelineBindPoint
  inputAttachmentCount*: uint32
  pInputAttachments*: ptr VkAttachmentReference
  colorAttachmentCount*: uint32
  pColorAttachments*: ptr VkAttachmentReference
  pResolveAttachments*: ptr VkAttachmentReference
  pDepthStencilAttachment*: ptr VkAttachmentReference
  preserveAttachmentCount*: uint32
  pPreserveAttachments*: ptr uint32


type VkSubpassDependency* = object
  srcSubpass*: uint32
  dstSubpass*: uint32
  srcStageMask*: VkPipelineStageFlags
  dstStageMask*: VkPipelineStageFlags
  srcAccessMask*: VkAccessFlags
  dstAccessMask*: VkAccessFlags
  dependencyFlags*: VkDependencyFlags


type VkRenderPassCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkRenderPassCreateFlags
  attachmentCount*: uint32
  pAttachments*: ptr VkAttachmentDescription
  subpassCount*: uint32
  pSubpasses*: ptr VkSubpassDescription
  dependencyCount*: uint32
  pDependencies*: ptr VkSubpassDependency


type VkEventCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkEventCreateFlags


type VkFenceCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkFenceCreateFlags


type VkPhysicalDeviceFeatures* = object
  robustBufferAccess*: VkBool32
  fullDrawIndexUint32*: VkBool32
  imageCubeArray*: VkBool32
  independentBlend*: VkBool32
  geometryShader*: VkBool32
  tessellationShader*: VkBool32
  sampleRateShading*: VkBool32
  dualSrcBlend*: VkBool32
  logicOp*: VkBool32
  multiDrawIndirect*: VkBool32
  drawIndirectFirstInstance*: VkBool32
  depthClamp*: VkBool32
  depthBiasClamp*: VkBool32
  fillModeNonSolid*: VkBool32
  depthBounds*: VkBool32
  wideLines*: VkBool32
  largePoints*: VkBool32
  alphaToOne*: VkBool32
  multiViewport*: VkBool32
  samplerAnisotropy*: VkBool32
  textureCompressionETC2*: VkBool32
  textureCompressionASTC_LDR*: VkBool32
  textureCompressionBC*: VkBool32
  occlusionQueryPrecise*: VkBool32
  pipelineStatisticsQuery*: VkBool32
  vertexPipelineStoresAndAtomics*: VkBool32
  fragmentStoresAndAtomics*: VkBool32
  shaderTessellationAndGeometryPointSize*: VkBool32
  shaderImageGatherExtended*: VkBool32
  shaderStorageImageExtendedFormats*: VkBool32
  shaderStorageImageMultisample*: VkBool32
  shaderStorageImageReadWithoutFormat*: VkBool32
  shaderStorageImageWriteWithoutFormat*: VkBool32
  shaderUniformBufferArrayDynamicIndexing*: VkBool32
  shaderSampledImageArrayDynamicIndexing*: VkBool32
  shaderStorageBufferArrayDynamicIndexing*: VkBool32
  shaderStorageImageArrayDynamicIndexing*: VkBool32
  shaderClipDistance*: VkBool32
  shaderCullDistance*: VkBool32
  shaderFloat64*: VkBool32
  shaderInt64*: VkBool32
  shaderInt16*: VkBool32
  shaderResourceResidency*: VkBool32
  shaderResourceMinLod*: VkBool32
  sparseBinding*: VkBool32
  sparseResidencyBuffer*: VkBool32
  sparseResidencyImage2D*: VkBool32
  sparseResidencyImage3D*: VkBool32
  sparseResidency2Samples*: VkBool32
  sparseResidency4Samples*: VkBool32
  sparseResidency8Samples*: VkBool32
  sparseResidency16Samples*: VkBool32
  sparseResidencyAliased*: VkBool32
  variableMultisampleRate*: VkBool32
  inheritedQueries*: VkBool32


type VkPhysicalDeviceSparseProperties* = object
  residencyStandard2DBlockShape*: VkBool32
  residencyStandard2DMultisampleBlockShape*: VkBool32
  residencyStandard3DBlockShape*: VkBool32
  residencyAlignedMipSize*: VkBool32
  residencyNonResidentStrict*: VkBool32


type VkPhysicalDeviceLimits* = object
  maxImageDimension1D*: uint32
  maxImageDimension2D*: uint32
  maxImageDimension3D*: uint32
  maxImageDimensionCube*: uint32
  maxImageArrayLayers*: uint32
  maxTexelBufferElements*: uint32
  maxUniformBufferRange*: uint32
  maxStorageBufferRange*: uint32
  maxPushConstantsSize*: uint32
  maxMemoryAllocationCount*: uint32
  maxSamplerAllocationCount*: uint32
  bufferImageGranularity*: VkDeviceSize
  sparseAddressSpaceSize*: VkDeviceSize
  maxBoundDescriptorSets*: uint32
  maxPerStageDescriptorSamplers*: uint32
  maxPerStageDescriptorUniformBuffers*: uint32
  maxPerStageDescriptorStorageBuffers*: uint32
  maxPerStageDescriptorSampledImages*: uint32
  maxPerStageDescriptorStorageImages*: uint32
  maxPerStageDescriptorInputAttachments*: uint32
  maxPerStageResources*: uint32
  maxDescriptorSetSamplers*: uint32
  maxDescriptorSetUniformBuffers*: uint32
  maxDescriptorSetUniformBuffersDynamic*: uint32
  maxDescriptorSetStorageBuffers*: uint32
  maxDescriptorSetStorageBuffersDynamic*: uint32
  maxDescriptorSetSampledImages*: uint32
  maxDescriptorSetStorageImages*: uint32
  maxDescriptorSetInputAttachments*: uint32
  maxVertexInputAttributes*: uint32
  maxVertexInputBindings*: uint32
  maxVertexInputAttributeOffset*: uint32
  maxVertexInputBindingStride*: uint32
  maxVertexOutputComponents*: uint32
  maxTessellationGenerationLevel*: uint32
  maxTessellationPatchSize*: uint32
  maxTessellationControlPerVertexInputComponents*: uint32
  maxTessellationControlPerVertexOutputComponents*: uint32
  maxTessellationControlPerPatchOutputComponents*: uint32
  maxTessellationControlTotalOutputComponents*: uint32
  maxTessellationEvaluationInputComponents*: uint32
  maxTessellationEvaluationOutputComponents*: uint32
  maxGeometryShaderInvocations*: uint32
  maxGeometryInputComponents*: uint32
  maxGeometryOutputComponents*: uint32
  maxGeometryOutputVertices*: uint32
  maxGeometryTotalOutputComponents*: uint32
  maxFragmentInputComponents*: uint32
  maxFragmentOutputAttachments*: uint32
  maxFragmentDualSrcAttachments*: uint32
  maxFragmentCombinedOutputResources*: uint32
  maxComputeSharedMemorySize*: uint32
  maxComputeWorkGroupCount*: array[3, uint32]
  maxComputeWorkGroupInvocations*: uint32
  maxComputeWorkGroupSize*: array[3, uint32]
  subPixelPrecisionBits*: uint32
  subTexelPrecisionBits*: uint32
  mipmapPrecisionBits*: uint32
  maxDrawIndexedIndexValue*: uint32
  maxDrawIndirectCount*: uint32
  maxSamplerLodBias*: float32
  maxSamplerAnisotropy*: float32
  maxViewports*: uint32
  maxViewportDimensions*: array[2, uint32]
  viewportBoundsRange*: array[2, float32]
  viewportSubPixelBits*: uint32
  minMemoryMapAlignment*: csize_t
  minTexelBufferOffsetAlignment*: VkDeviceSize
  minUniformBufferOffsetAlignment*: VkDeviceSize
  minStorageBufferOffsetAlignment*: VkDeviceSize
  minTexelOffset*: int32
  maxTexelOffset*: uint32
  minTexelGatherOffset*: int32
  maxTexelGatherOffset*: uint32
  minInterpolationOffset*: float32
  maxInterpolationOffset*: float32
  subPixelInterpolationOffsetBits*: uint32
  maxFramebufferWidth*: uint32
  maxFramebufferHeight*: uint32
  maxFramebufferLayers*: uint32
  framebufferColorSampleCounts*: VkSampleCountFlags
  framebufferDepthSampleCounts*: VkSampleCountFlags
  framebufferStencilSampleCounts*: VkSampleCountFlags
  framebufferNoAttachmentsSampleCounts*: VkSampleCountFlags
  maxColorAttachments*: uint32
  sampledImageColorSampleCounts*: VkSampleCountFlags
  sampledImageIntegerSampleCounts*: VkSampleCountFlags
  sampledImageDepthSampleCounts*: VkSampleCountFlags
  sampledImageStencilSampleCounts*: VkSampleCountFlags
  storageImageSampleCounts*: VkSampleCountFlags
  maxSampleMaskWords*: uint32
  timestampComputeAndGraphics*: VkBool32
  timestampPeriod*: float32
  maxClipDistances*: uint32
  maxCullDistances*: uint32
  maxCombinedClipAndCullDistances*: uint32
  discreteQueuePriorities*: uint32
  pointSizeRange*: array[2, float32]
  lineWidthRange*: array[2, float32]
  pointSizeGranularity*: float32
  lineWidthGranularity*: float32
  strictLines*: VkBool32
  standardSampleLocations*: VkBool32
  optimalBufferCopyOffsetAlignment*: VkDeviceSize
  optimalBufferCopyRowPitchAlignment*: VkDeviceSize
  nonCoherentAtomSize*: VkDeviceSize


type VkSemaphoreCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkSemaphoreCreateFlags


type VkQueryPoolCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkQueryPoolCreateFlags
  queryType*: VkQueryType
  queryCount*: uint32
  pipelineStatistics*: VkQueryPipelineStatisticFlags


type VkFramebufferCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkFramebufferCreateFlags
  renderPass*: VkRenderPass
  attachmentCount*: uint32
  pAttachments*: ptr VkImageView
  width*: uint32
  height*: uint32
  layers*: uint32


type VkDrawIndirectCommand* = object
  vertexCount*: uint32
  instanceCount*: uint32
  firstVertex*: uint32
  firstInstance*: uint32


type VkDrawIndexedIndirectCommand* = object
  indexCount*: uint32
  instanceCount*: uint32
  firstIndex*: uint32
  vertexOffset*: int32
  firstInstance*: uint32


type VkDispatchIndirectCommand* = object
  x*: uint32
  y*: uint32
  z*: uint32


type VkSubmitInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  waitSemaphoreCount*: uint32
  pWaitSemaphores*: ptr VkSemaphore
  pWaitDstStageMask*: ptr VkPipelineStageFlags
  commandBufferCount*: uint32
  pCommandBuffers*: ptr VkCommandBuffer
  signalSemaphoreCount*: uint32
  pSignalSemaphores*: ptr VkSemaphore


type VkDevicePrivateDataCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  privateDataSlotRequestCount*: uint32


type VkPrivateDataSlotCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkPrivateDataSlotCreateFlags


type VkPhysicalDevicePrivateDataFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  privateData*: VkBool32


type VkPhysicalDeviceFeatures2* = object
  sType*: VkStructureType
  pNext*: pointer
  features*: VkPhysicalDeviceFeatures


type VkPhysicalDeviceProperties2* = object
  sType*: VkStructureType
  pNext*: pointer
  properties*: VkPhysicalDeviceProperties


type VkFormatProperties2* = object
  sType*: VkStructureType
  pNext*: pointer
  formatProperties*: VkFormatProperties


type VkImageFormatProperties2* = object
  sType*: VkStructureType
  pNext*: pointer
  imageFormatProperties*: VkImageFormatProperties


type VkPhysicalDeviceImageFormatInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  format*: VkFormat
  `type`*: VkImageType
  tiling*: VkImageTiling
  usage*: VkImageUsageFlags
  flags*: VkImageCreateFlags


type VkQueueFamilyProperties2* = object
  sType*: VkStructureType
  pNext*: pointer
  queueFamilyProperties*: VkQueueFamilyProperties


type VkPhysicalDeviceMemoryProperties2* = object
  sType*: VkStructureType
  pNext*: pointer
  memoryProperties*: VkPhysicalDeviceMemoryProperties


type VkSparseImageFormatProperties2* = object
  sType*: VkStructureType
  pNext*: pointer
  properties*: VkSparseImageFormatProperties


type VkPhysicalDeviceSparseImageFormatInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  format*: VkFormat
  `type`*: VkImageType
  samples*: VkSampleCountFlagBits
  usage*: VkImageUsageFlags
  tiling*: VkImageTiling


type VkConformanceVersion* = object
  major*: uint8
  minor*: uint8
  subminor*: uint8
  patch*: uint8


type VkPhysicalDeviceDriverProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  driverID*: VkDriverId
  driverName*: array[VK_MAX_DRIVER_NAME_SIZE, char]
  driverInfo*: array[VK_MAX_DRIVER_INFO_SIZE, char]
  conformanceVersion*: VkConformanceVersion


type VkPhysicalDeviceVariablePointersFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  variablePointersStorageBuffer*: VkBool32
  variablePointers*: VkBool32


type VkExternalMemoryProperties* = object
  externalMemoryFeatures*: VkExternalMemoryFeatureFlags
  exportFromImportedHandleTypes*: VkExternalMemoryHandleTypeFlags
  compatibleHandleTypes*: VkExternalMemoryHandleTypeFlags


type VkPhysicalDeviceExternalImageFormatInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  handleType*: VkExternalMemoryHandleTypeFlagBits


type VkExternalImageFormatProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  externalMemoryProperties*: VkExternalMemoryProperties


type VkPhysicalDeviceExternalBufferInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkBufferCreateFlags
  usage*: VkBufferUsageFlags
  handleType*: VkExternalMemoryHandleTypeFlagBits


type VkExternalBufferProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  externalMemoryProperties*: VkExternalMemoryProperties


type VkPhysicalDeviceIDProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  deviceUUID*: array[VK_UUID_SIZE, uint8]
  driverUUID*: array[VK_UUID_SIZE, uint8]
  deviceLUID*: array[VK_LUID_SIZE, uint8]
  deviceNodeMask*: uint32
  deviceLUIDValid*: VkBool32


type VkExternalMemoryImageCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  handleTypes*: VkExternalMemoryHandleTypeFlags


type VkExternalMemoryBufferCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  handleTypes*: VkExternalMemoryHandleTypeFlags


type VkExportMemoryAllocateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  handleTypes*: VkExternalMemoryHandleTypeFlags


type VkPhysicalDeviceExternalSemaphoreInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  handleType*: VkExternalSemaphoreHandleTypeFlagBits


type VkExternalSemaphoreProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  exportFromImportedHandleTypes*: VkExternalSemaphoreHandleTypeFlags
  compatibleHandleTypes*: VkExternalSemaphoreHandleTypeFlags
  externalSemaphoreFeatures*: VkExternalSemaphoreFeatureFlags


type VkExportSemaphoreCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  handleTypes*: VkExternalSemaphoreHandleTypeFlags


type VkPhysicalDeviceExternalFenceInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  handleType*: VkExternalFenceHandleTypeFlagBits


type VkExternalFenceProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  exportFromImportedHandleTypes*: VkExternalFenceHandleTypeFlags
  compatibleHandleTypes*: VkExternalFenceHandleTypeFlags
  externalFenceFeatures*: VkExternalFenceFeatureFlags


type VkExportFenceCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  handleTypes*: VkExternalFenceHandleTypeFlags


type VkPhysicalDeviceMultiviewFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  multiview*: VkBool32
  multiviewGeometryShader*: VkBool32
  multiviewTessellationShader*: VkBool32


type VkPhysicalDeviceMultiviewProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  maxMultiviewViewCount*: uint32
  maxMultiviewInstanceIndex*: uint32


type VkRenderPassMultiviewCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  subpassCount*: uint32
  pViewMasks*: ptr uint32
  dependencyCount*: uint32
  pViewOffsets*: ptr int32
  correlationMaskCount*: uint32
  pCorrelationMasks*: ptr uint32


type VkPhysicalDeviceGroupProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  physicalDeviceCount*: uint32
  physicalDevices*: array[VK_MAX_DEVICE_GROUP_SIZE, VkPhysicalDevice]
  subsetAllocation*: VkBool32


type VkMemoryAllocateFlagsInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkMemoryAllocateFlags
  deviceMask*: uint32


type VkBindBufferMemoryInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  buffer*: VkBuffer
  memory*: VkDeviceMemory
  memoryOffset*: VkDeviceSize


type VkBindBufferMemoryDeviceGroupInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  deviceIndexCount*: uint32
  pDeviceIndices*: ptr uint32


type VkBindImageMemoryInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  image*: VkImage
  memory*: VkDeviceMemory
  memoryOffset*: VkDeviceSize


type VkBindImageMemoryDeviceGroupInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  deviceIndexCount*: uint32
  pDeviceIndices*: ptr uint32
  splitInstanceBindRegionCount*: uint32
  pSplitInstanceBindRegions*: ptr VkRect2D


type VkDeviceGroupRenderPassBeginInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  deviceMask*: uint32
  deviceRenderAreaCount*: uint32
  pDeviceRenderAreas*: ptr VkRect2D


type VkDeviceGroupCommandBufferBeginInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  deviceMask*: uint32


type VkDeviceGroupSubmitInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  waitSemaphoreCount*: uint32
  pWaitSemaphoreDeviceIndices*: ptr uint32
  commandBufferCount*: uint32
  pCommandBufferDeviceMasks*: ptr uint32
  signalSemaphoreCount*: uint32
  pSignalSemaphoreDeviceIndices*: ptr uint32


type VkDeviceGroupBindSparseInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  resourceDeviceIndex*: uint32
  memoryDeviceIndex*: uint32


type VkDeviceGroupDeviceCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  physicalDeviceCount*: uint32
  pPhysicalDevices*: ptr VkPhysicalDevice


type VkDescriptorUpdateTemplateEntry* = object
  dstBinding*: uint32
  dstArrayElement*: uint32
  descriptorCount*: uint32
  descriptorType*: VkDescriptorType
  offset*: csize_t
  stride*: csize_t


type VkDescriptorUpdateTemplateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkDescriptorUpdateTemplateCreateFlags
  descriptorUpdateEntryCount*: uint32
  pDescriptorUpdateEntries*: ptr VkDescriptorUpdateTemplateEntry
  templateType*: VkDescriptorUpdateTemplateType
  descriptorSetLayout*: VkDescriptorSetLayout
  pipelineBindPoint*: VkPipelineBindPoint
  pipelineLayout*: VkPipelineLayout
  set*: uint32


type VkInputAttachmentAspectReference* = object
  subpass*: uint32
  inputAttachmentIndex*: uint32
  aspectMask*: VkImageAspectFlags


type VkRenderPassInputAttachmentAspectCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  aspectReferenceCount*: uint32
  pAspectReferences*: ptr VkInputAttachmentAspectReference


type VkPhysicalDevice16BitStorageFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  storageBuffer16BitAccess*: VkBool32
  uniformAndStorageBuffer16BitAccess*: VkBool32
  storagePushConstant16*: VkBool32
  storageInputOutput16*: VkBool32


type VkPhysicalDeviceSubgroupProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  subgroupSize*: uint32
  supportedStages*: VkShaderStageFlags
  supportedOperations*: VkSubgroupFeatureFlags
  quadOperationsInAllStages*: VkBool32


type VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderSubgroupExtendedTypes*: VkBool32


type VkBufferMemoryRequirementsInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  buffer*: VkBuffer


type VkDeviceBufferMemoryRequirements* = object
  sType*: VkStructureType
  pNext*: pointer
  pCreateInfo*: ptr VkBufferCreateInfo


type VkImageMemoryRequirementsInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  image*: VkImage


type VkImageSparseMemoryRequirementsInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  image*: VkImage


type VkDeviceImageMemoryRequirements* = object
  sType*: VkStructureType
  pNext*: pointer
  pCreateInfo*: ptr VkImageCreateInfo
  planeAspect*: VkImageAspectFlagBits


type VkMemoryRequirements2* = object
  sType*: VkStructureType
  pNext*: pointer
  memoryRequirements*: VkMemoryRequirements


type VkSparseImageMemoryRequirements2* = object
  sType*: VkStructureType
  pNext*: pointer
  memoryRequirements*: VkSparseImageMemoryRequirements


type VkPhysicalDevicePointClippingProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  pointClippingBehavior*: VkPointClippingBehavior


type VkMemoryDedicatedRequirements* = object
  sType*: VkStructureType
  pNext*: pointer
  prefersDedicatedAllocation*: VkBool32
  requiresDedicatedAllocation*: VkBool32


type VkMemoryDedicatedAllocateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  image*: VkImage
  buffer*: VkBuffer


type VkImageViewUsageCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  usage*: VkImageUsageFlags


type VkPipelineTessellationDomainOriginStateCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  domainOrigin*: VkTessellationDomainOrigin


type VkSamplerYcbcrConversionInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  conversion*: VkSamplerYcbcrConversion


type VkSamplerYcbcrConversionCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  format*: VkFormat
  ycbcrModel*: VkSamplerYcbcrModelConversion
  ycbcrRange*: VkSamplerYcbcrRange
  components*: VkComponentMapping
  xChromaOffset*: VkChromaLocation
  yChromaOffset*: VkChromaLocation
  chromaFilter*: VkFilter
  forceExplicitReconstruction*: VkBool32


type VkBindImagePlaneMemoryInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  planeAspect*: VkImageAspectFlagBits


type VkImagePlaneMemoryRequirementsInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  planeAspect*: VkImageAspectFlagBits


type VkPhysicalDeviceSamplerYcbcrConversionFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  samplerYcbcrConversion*: VkBool32


type VkSamplerYcbcrConversionImageFormatProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  combinedImageSamplerDescriptorCount*: uint32


type VkProtectedSubmitInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  protectedSubmit*: VkBool32


type VkPhysicalDeviceProtectedMemoryFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  protectedMemory*: VkBool32


type VkPhysicalDeviceProtectedMemoryProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  protectedNoFault*: VkBool32


type VkDeviceQueueInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkDeviceQueueCreateFlags
  queueFamilyIndex*: uint32
  queueIndex*: uint32


type VkPhysicalDeviceSamplerFilterMinmaxProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  filterMinmaxSingleComponentFormats*: VkBool32
  filterMinmaxImageComponentMapping*: VkBool32


type VkSamplerReductionModeCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  reductionMode*: VkSamplerReductionMode


type VkPhysicalDeviceInlineUniformBlockFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  inlineUniformBlock*: VkBool32
  descriptorBindingInlineUniformBlockUpdateAfterBind*: VkBool32


type VkPhysicalDeviceInlineUniformBlockProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  maxInlineUniformBlockSize*: uint32
  maxPerStageDescriptorInlineUniformBlocks*: uint32
  maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks*: uint32
  maxDescriptorSetInlineUniformBlocks*: uint32
  maxDescriptorSetUpdateAfterBindInlineUniformBlocks*: uint32


type VkWriteDescriptorSetInlineUniformBlock* = object
  sType*: VkStructureType
  pNext*: pointer
  dataSize*: uint32
  pData*: pointer


type VkDescriptorPoolInlineUniformBlockCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  maxInlineUniformBlockBindings*: uint32


type VkImageFormatListCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  viewFormatCount*: uint32
  pViewFormats*: ptr VkFormat


type VkPhysicalDeviceMaintenance3Properties* = object
  sType*: VkStructureType
  pNext*: pointer
  maxPerSetDescriptors*: uint32
  maxMemoryAllocationSize*: VkDeviceSize


type VkPhysicalDeviceMaintenance4Features* = object
  sType*: VkStructureType
  pNext*: pointer
  maintenance4*: VkBool32


type VkPhysicalDeviceMaintenance4Properties* = object
  sType*: VkStructureType
  pNext*: pointer
  maxBufferSize*: VkDeviceSize


type VkDescriptorSetLayoutSupport* = object
  sType*: VkStructureType
  pNext*: pointer
  supported*: VkBool32


type VkPhysicalDeviceShaderDrawParametersFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderDrawParameters*: VkBool32


type VkPhysicalDeviceShaderFloat16Int8Features* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderFloat16*: VkBool32
  shaderInt8*: VkBool32


type VkPhysicalDeviceFloatControlsProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  denormBehaviorIndependence*: VkShaderFloatControlsIndependence
  roundingModeIndependence*: VkShaderFloatControlsIndependence
  shaderSignedZeroInfNanPreserveFloat16*: VkBool32
  shaderSignedZeroInfNanPreserveFloat32*: VkBool32
  shaderSignedZeroInfNanPreserveFloat64*: VkBool32
  shaderDenormPreserveFloat16*: VkBool32
  shaderDenormPreserveFloat32*: VkBool32
  shaderDenormPreserveFloat64*: VkBool32
  shaderDenormFlushToZeroFloat16*: VkBool32
  shaderDenormFlushToZeroFloat32*: VkBool32
  shaderDenormFlushToZeroFloat64*: VkBool32
  shaderRoundingModeRTEFloat16*: VkBool32
  shaderRoundingModeRTEFloat32*: VkBool32
  shaderRoundingModeRTEFloat64*: VkBool32
  shaderRoundingModeRTZFloat16*: VkBool32
  shaderRoundingModeRTZFloat32*: VkBool32
  shaderRoundingModeRTZFloat64*: VkBool32


type VkPhysicalDeviceHostQueryResetFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  hostQueryReset*: VkBool32


type VkPhysicalDeviceDescriptorIndexingFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderInputAttachmentArrayDynamicIndexing*: VkBool32
  shaderUniformTexelBufferArrayDynamicIndexing*: VkBool32
  shaderStorageTexelBufferArrayDynamicIndexing*: VkBool32
  shaderUniformBufferArrayNonUniformIndexing*: VkBool32
  shaderSampledImageArrayNonUniformIndexing*: VkBool32
  shaderStorageBufferArrayNonUniformIndexing*: VkBool32
  shaderStorageImageArrayNonUniformIndexing*: VkBool32
  shaderInputAttachmentArrayNonUniformIndexing*: VkBool32
  shaderUniformTexelBufferArrayNonUniformIndexing*: VkBool32
  shaderStorageTexelBufferArrayNonUniformIndexing*: VkBool32
  descriptorBindingUniformBufferUpdateAfterBind*: VkBool32
  descriptorBindingSampledImageUpdateAfterBind*: VkBool32
  descriptorBindingStorageImageUpdateAfterBind*: VkBool32
  descriptorBindingStorageBufferUpdateAfterBind*: VkBool32
  descriptorBindingUniformTexelBufferUpdateAfterBind*: VkBool32
  descriptorBindingStorageTexelBufferUpdateAfterBind*: VkBool32
  descriptorBindingUpdateUnusedWhilePending*: VkBool32
  descriptorBindingPartiallyBound*: VkBool32
  descriptorBindingVariableDescriptorCount*: VkBool32
  runtimeDescriptorArray*: VkBool32


type VkPhysicalDeviceDescriptorIndexingProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  maxUpdateAfterBindDescriptorsInAllPools*: uint32
  shaderUniformBufferArrayNonUniformIndexingNative*: VkBool32
  shaderSampledImageArrayNonUniformIndexingNative*: VkBool32
  shaderStorageBufferArrayNonUniformIndexingNative*: VkBool32
  shaderStorageImageArrayNonUniformIndexingNative*: VkBool32
  shaderInputAttachmentArrayNonUniformIndexingNative*: VkBool32
  robustBufferAccessUpdateAfterBind*: VkBool32
  quadDivergentImplicitLod*: VkBool32
  maxPerStageDescriptorUpdateAfterBindSamplers*: uint32
  maxPerStageDescriptorUpdateAfterBindUniformBuffers*: uint32
  maxPerStageDescriptorUpdateAfterBindStorageBuffers*: uint32
  maxPerStageDescriptorUpdateAfterBindSampledImages*: uint32
  maxPerStageDescriptorUpdateAfterBindStorageImages*: uint32
  maxPerStageDescriptorUpdateAfterBindInputAttachments*: uint32
  maxPerStageUpdateAfterBindResources*: uint32
  maxDescriptorSetUpdateAfterBindSamplers*: uint32
  maxDescriptorSetUpdateAfterBindUniformBuffers*: uint32
  maxDescriptorSetUpdateAfterBindUniformBuffersDynamic*: uint32
  maxDescriptorSetUpdateAfterBindStorageBuffers*: uint32
  maxDescriptorSetUpdateAfterBindStorageBuffersDynamic*: uint32
  maxDescriptorSetUpdateAfterBindSampledImages*: uint32
  maxDescriptorSetUpdateAfterBindStorageImages*: uint32
  maxDescriptorSetUpdateAfterBindInputAttachments*: uint32


type VkDescriptorSetLayoutBindingFlagsCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  bindingCount*: uint32
  pBindingFlags*: ptr VkDescriptorBindingFlags


type VkDescriptorSetVariableDescriptorCountAllocateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  descriptorSetCount*: uint32
  pDescriptorCounts*: ptr uint32


type VkDescriptorSetVariableDescriptorCountLayoutSupport* = object
  sType*: VkStructureType
  pNext*: pointer
  maxVariableDescriptorCount*: uint32


type VkAttachmentDescription2* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkAttachmentDescriptionFlags
  format*: VkFormat
  samples*: VkSampleCountFlagBits
  loadOp*: VkAttachmentLoadOp
  storeOp*: VkAttachmentStoreOp
  stencilLoadOp*: VkAttachmentLoadOp
  stencilStoreOp*: VkAttachmentStoreOp
  initialLayout*: VkImageLayout
  finalLayout*: VkImageLayout


type VkAttachmentReference2* = object
  sType*: VkStructureType
  pNext*: pointer
  attachment*: uint32
  layout*: VkImageLayout
  aspectMask*: VkImageAspectFlags


type VkSubpassDescription2* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkSubpassDescriptionFlags
  pipelineBindPoint*: VkPipelineBindPoint
  viewMask*: uint32
  inputAttachmentCount*: uint32
  pInputAttachments*: ptr VkAttachmentReference2
  colorAttachmentCount*: uint32
  pColorAttachments*: ptr VkAttachmentReference2
  pResolveAttachments*: ptr VkAttachmentReference2
  pDepthStencilAttachment*: ptr VkAttachmentReference2
  preserveAttachmentCount*: uint32
  pPreserveAttachments*: ptr uint32


type VkSubpassDependency2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcSubpass*: uint32
  dstSubpass*: uint32
  srcStageMask*: VkPipelineStageFlags
  dstStageMask*: VkPipelineStageFlags
  srcAccessMask*: VkAccessFlags
  dstAccessMask*: VkAccessFlags
  dependencyFlags*: VkDependencyFlags
  viewOffset*: int32


type VkRenderPassCreateInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkRenderPassCreateFlags
  attachmentCount*: uint32
  pAttachments*: ptr VkAttachmentDescription2
  subpassCount*: uint32
  pSubpasses*: ptr VkSubpassDescription2
  dependencyCount*: uint32
  pDependencies*: ptr VkSubpassDependency2
  correlatedViewMaskCount*: uint32
  pCorrelatedViewMasks*: ptr uint32


type VkSubpassBeginInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  contents*: VkSubpassContents


type VkSubpassEndInfo* = object
  sType*: VkStructureType
  pNext*: pointer


type VkPhysicalDeviceTimelineSemaphoreFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  timelineSemaphore*: VkBool32


type VkPhysicalDeviceTimelineSemaphoreProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  maxTimelineSemaphoreValueDifference*: uint64


type VkSemaphoreTypeCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  semaphoreType*: VkSemaphoreType
  initialValue*: uint64


type VkTimelineSemaphoreSubmitInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  waitSemaphoreValueCount*: uint32
  pWaitSemaphoreValues*: ptr uint64
  signalSemaphoreValueCount*: uint32
  pSignalSemaphoreValues*: ptr uint64


type VkSemaphoreWaitInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkSemaphoreWaitFlags
  semaphoreCount*: uint32
  pSemaphores*: ptr VkSemaphore
  pValues*: ptr uint64


type VkSemaphoreSignalInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  semaphore*: VkSemaphore
  value*: uint64


type VkPhysicalDevice8BitStorageFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  storageBuffer8BitAccess*: VkBool32
  uniformAndStorageBuffer8BitAccess*: VkBool32
  storagePushConstant8*: VkBool32


type VkPhysicalDeviceVulkanMemoryModelFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  vulkanMemoryModel*: VkBool32
  vulkanMemoryModelDeviceScope*: VkBool32
  vulkanMemoryModelAvailabilityVisibilityChains*: VkBool32


type VkPhysicalDeviceShaderAtomicInt64Features* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderBufferInt64Atomics*: VkBool32
  shaderSharedInt64Atomics*: VkBool32


type VkPhysicalDeviceDepthStencilResolveProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  supportedDepthResolveModes*: VkResolveModeFlags
  supportedStencilResolveModes*: VkResolveModeFlags
  independentResolveNone*: VkBool32
  independentResolve*: VkBool32


type VkSubpassDescriptionDepthStencilResolve* = object
  sType*: VkStructureType
  pNext*: pointer
  depthResolveMode*: VkResolveModeFlagBits
  stencilResolveMode*: VkResolveModeFlagBits
  pDepthStencilResolveAttachment*: ptr VkAttachmentReference2


type VkImageStencilUsageCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  stencilUsage*: VkImageUsageFlags


type VkPhysicalDeviceScalarBlockLayoutFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  scalarBlockLayout*: VkBool32


type VkPhysicalDeviceUniformBufferStandardLayoutFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  uniformBufferStandardLayout*: VkBool32


type VkPhysicalDeviceBufferDeviceAddressFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  bufferDeviceAddress*: VkBool32
  bufferDeviceAddressCaptureReplay*: VkBool32
  bufferDeviceAddressMultiDevice*: VkBool32


type VkBufferDeviceAddressInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  buffer*: VkBuffer


type VkBufferOpaqueCaptureAddressCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  opaqueCaptureAddress*: uint64


type VkPhysicalDeviceImagelessFramebufferFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  imagelessFramebuffer*: VkBool32


type VkFramebufferAttachmentsCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  attachmentImageInfoCount*: uint32
  pAttachmentImageInfos*: ptr VkFramebufferAttachmentImageInfo


type VkFramebufferAttachmentImageInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkImageCreateFlags
  usage*: VkImageUsageFlags
  width*: uint32
  height*: uint32
  layerCount*: uint32
  viewFormatCount*: uint32
  pViewFormats*: ptr VkFormat


type VkRenderPassAttachmentBeginInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  attachmentCount*: uint32
  pAttachments*: ptr VkImageView


type VkPhysicalDeviceTextureCompressionASTCHDRFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  textureCompressionASTC_HDR*: VkBool32


type VkPipelineCreationFeedback* = object
  flags*: VkPipelineCreationFeedbackFlags
  duration*: uint64


type VkPipelineCreationFeedbackCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  pPipelineCreationFeedback*: ptr VkPipelineCreationFeedback
  pipelineStageCreationFeedbackCount*: uint32
  pPipelineStageCreationFeedbacks*: ptr VkPipelineCreationFeedback


type VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  separateDepthStencilLayouts*: VkBool32


type VkAttachmentReferenceStencilLayout* = object
  sType*: VkStructureType
  pNext*: pointer
  stencilLayout*: VkImageLayout


type VkAttachmentDescriptionStencilLayout* = object
  sType*: VkStructureType
  pNext*: pointer
  stencilInitialLayout*: VkImageLayout
  stencilFinalLayout*: VkImageLayout


type VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderDemoteToHelperInvocation*: VkBool32


type VkPhysicalDeviceTexelBufferAlignmentProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  storageTexelBufferOffsetAlignmentBytes*: VkDeviceSize
  storageTexelBufferOffsetSingleTexelAlignment*: VkBool32
  uniformTexelBufferOffsetAlignmentBytes*: VkDeviceSize
  uniformTexelBufferOffsetSingleTexelAlignment*: VkBool32


type VkPhysicalDeviceSubgroupSizeControlFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  subgroupSizeControl*: VkBool32
  computeFullSubgroups*: VkBool32


type VkPhysicalDeviceSubgroupSizeControlProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  minSubgroupSize*: uint32
  maxSubgroupSize*: uint32
  maxComputeWorkgroupSubgroups*: uint32
  requiredSubgroupSizeStages*: VkShaderStageFlags


type VkPipelineShaderStageRequiredSubgroupSizeCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  requiredSubgroupSize*: uint32


type VkMemoryOpaqueCaptureAddressAllocateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  opaqueCaptureAddress*: uint64


type VkDeviceMemoryOpaqueCaptureAddressInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  memory*: VkDeviceMemory


type VkPhysicalDevicePipelineCreationCacheControlFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  pipelineCreationCacheControl*: VkBool32


type VkPhysicalDeviceVulkan11Features* = object
  sType*: VkStructureType
  pNext*: pointer
  storageBuffer16BitAccess*: VkBool32
  uniformAndStorageBuffer16BitAccess*: VkBool32
  storagePushConstant16*: VkBool32
  storageInputOutput16*: VkBool32
  multiview*: VkBool32
  multiviewGeometryShader*: VkBool32
  multiviewTessellationShader*: VkBool32
  variablePointersStorageBuffer*: VkBool32
  variablePointers*: VkBool32
  protectedMemory*: VkBool32
  samplerYcbcrConversion*: VkBool32
  shaderDrawParameters*: VkBool32


type VkPhysicalDeviceVulkan11Properties* = object
  sType*: VkStructureType
  pNext*: pointer
  deviceUUID*: array[VK_UUID_SIZE, uint8]
  driverUUID*: array[VK_UUID_SIZE, uint8]
  deviceLUID*: array[VK_LUID_SIZE, uint8]
  deviceNodeMask*: uint32
  deviceLUIDValid*: VkBool32
  subgroupSize*: uint32
  subgroupSupportedStages*: VkShaderStageFlags
  subgroupSupportedOperations*: VkSubgroupFeatureFlags
  subgroupQuadOperationsInAllStages*: VkBool32
  pointClippingBehavior*: VkPointClippingBehavior
  maxMultiviewViewCount*: uint32
  maxMultiviewInstanceIndex*: uint32
  protectedNoFault*: VkBool32
  maxPerSetDescriptors*: uint32
  maxMemoryAllocationSize*: VkDeviceSize


type VkPhysicalDeviceVulkan12Features* = object
  sType*: VkStructureType
  pNext*: pointer
  samplerMirrorClampToEdge*: VkBool32
  drawIndirectCount*: VkBool32
  storageBuffer8BitAccess*: VkBool32
  uniformAndStorageBuffer8BitAccess*: VkBool32
  storagePushConstant8*: VkBool32
  shaderBufferInt64Atomics*: VkBool32
  shaderSharedInt64Atomics*: VkBool32
  shaderFloat16*: VkBool32
  shaderInt8*: VkBool32
  descriptorIndexing*: VkBool32
  shaderInputAttachmentArrayDynamicIndexing*: VkBool32
  shaderUniformTexelBufferArrayDynamicIndexing*: VkBool32
  shaderStorageTexelBufferArrayDynamicIndexing*: VkBool32
  shaderUniformBufferArrayNonUniformIndexing*: VkBool32
  shaderSampledImageArrayNonUniformIndexing*: VkBool32
  shaderStorageBufferArrayNonUniformIndexing*: VkBool32
  shaderStorageImageArrayNonUniformIndexing*: VkBool32
  shaderInputAttachmentArrayNonUniformIndexing*: VkBool32
  shaderUniformTexelBufferArrayNonUniformIndexing*: VkBool32
  shaderStorageTexelBufferArrayNonUniformIndexing*: VkBool32
  descriptorBindingUniformBufferUpdateAfterBind*: VkBool32
  descriptorBindingSampledImageUpdateAfterBind*: VkBool32
  descriptorBindingStorageImageUpdateAfterBind*: VkBool32
  descriptorBindingStorageBufferUpdateAfterBind*: VkBool32
  descriptorBindingUniformTexelBufferUpdateAfterBind*: VkBool32
  descriptorBindingStorageTexelBufferUpdateAfterBind*: VkBool32
  descriptorBindingUpdateUnusedWhilePending*: VkBool32
  descriptorBindingPartiallyBound*: VkBool32
  descriptorBindingVariableDescriptorCount*: VkBool32
  runtimeDescriptorArray*: VkBool32
  samplerFilterMinmax*: VkBool32
  scalarBlockLayout*: VkBool32
  imagelessFramebuffer*: VkBool32
  uniformBufferStandardLayout*: VkBool32
  shaderSubgroupExtendedTypes*: VkBool32
  separateDepthStencilLayouts*: VkBool32
  hostQueryReset*: VkBool32
  timelineSemaphore*: VkBool32
  bufferDeviceAddress*: VkBool32
  bufferDeviceAddressCaptureReplay*: VkBool32
  bufferDeviceAddressMultiDevice*: VkBool32
  vulkanMemoryModel*: VkBool32
  vulkanMemoryModelDeviceScope*: VkBool32
  vulkanMemoryModelAvailabilityVisibilityChains*: VkBool32
  shaderOutputViewportIndex*: VkBool32
  shaderOutputLayer*: VkBool32
  subgroupBroadcastDynamicId*: VkBool32


type VkPhysicalDeviceVulkan12Properties* = object
  sType*: VkStructureType
  pNext*: pointer
  driverID*: VkDriverId
  driverName*: array[VK_MAX_DRIVER_NAME_SIZE, char]
  driverInfo*: array[VK_MAX_DRIVER_INFO_SIZE, char]
  conformanceVersion*: VkConformanceVersion
  denormBehaviorIndependence*: VkShaderFloatControlsIndependence
  roundingModeIndependence*: VkShaderFloatControlsIndependence
  shaderSignedZeroInfNanPreserveFloat16*: VkBool32
  shaderSignedZeroInfNanPreserveFloat32*: VkBool32
  shaderSignedZeroInfNanPreserveFloat64*: VkBool32
  shaderDenormPreserveFloat16*: VkBool32
  shaderDenormPreserveFloat32*: VkBool32
  shaderDenormPreserveFloat64*: VkBool32
  shaderDenormFlushToZeroFloat16*: VkBool32
  shaderDenormFlushToZeroFloat32*: VkBool32
  shaderDenormFlushToZeroFloat64*: VkBool32
  shaderRoundingModeRTEFloat16*: VkBool32
  shaderRoundingModeRTEFloat32*: VkBool32
  shaderRoundingModeRTEFloat64*: VkBool32
  shaderRoundingModeRTZFloat16*: VkBool32
  shaderRoundingModeRTZFloat32*: VkBool32
  shaderRoundingModeRTZFloat64*: VkBool32
  maxUpdateAfterBindDescriptorsInAllPools*: uint32
  shaderUniformBufferArrayNonUniformIndexingNative*: VkBool32
  shaderSampledImageArrayNonUniformIndexingNative*: VkBool32
  shaderStorageBufferArrayNonUniformIndexingNative*: VkBool32
  shaderStorageImageArrayNonUniformIndexingNative*: VkBool32
  shaderInputAttachmentArrayNonUniformIndexingNative*: VkBool32
  robustBufferAccessUpdateAfterBind*: VkBool32
  quadDivergentImplicitLod*: VkBool32
  maxPerStageDescriptorUpdateAfterBindSamplers*: uint32
  maxPerStageDescriptorUpdateAfterBindUniformBuffers*: uint32
  maxPerStageDescriptorUpdateAfterBindStorageBuffers*: uint32
  maxPerStageDescriptorUpdateAfterBindSampledImages*: uint32
  maxPerStageDescriptorUpdateAfterBindStorageImages*: uint32
  maxPerStageDescriptorUpdateAfterBindInputAttachments*: uint32
  maxPerStageUpdateAfterBindResources*: uint32
  maxDescriptorSetUpdateAfterBindSamplers*: uint32
  maxDescriptorSetUpdateAfterBindUniformBuffers*: uint32
  maxDescriptorSetUpdateAfterBindUniformBuffersDynamic*: uint32
  maxDescriptorSetUpdateAfterBindStorageBuffers*: uint32
  maxDescriptorSetUpdateAfterBindStorageBuffersDynamic*: uint32
  maxDescriptorSetUpdateAfterBindSampledImages*: uint32
  maxDescriptorSetUpdateAfterBindStorageImages*: uint32
  maxDescriptorSetUpdateAfterBindInputAttachments*: uint32
  supportedDepthResolveModes*: VkResolveModeFlags
  supportedStencilResolveModes*: VkResolveModeFlags
  independentResolveNone*: VkBool32
  independentResolve*: VkBool32
  filterMinmaxSingleComponentFormats*: VkBool32
  filterMinmaxImageComponentMapping*: VkBool32
  maxTimelineSemaphoreValueDifference*: uint64
  framebufferIntegerColorSampleCounts*: VkSampleCountFlags


type VkPhysicalDeviceVulkan13Features* = object
  sType*: VkStructureType
  pNext*: pointer
  robustImageAccess*: VkBool32
  inlineUniformBlock*: VkBool32
  descriptorBindingInlineUniformBlockUpdateAfterBind*: VkBool32
  pipelineCreationCacheControl*: VkBool32
  privateData*: VkBool32
  shaderDemoteToHelperInvocation*: VkBool32
  shaderTerminateInvocation*: VkBool32
  subgroupSizeControl*: VkBool32
  computeFullSubgroups*: VkBool32
  synchronization2*: VkBool32
  textureCompressionASTC_HDR*: VkBool32
  shaderZeroInitializeWorkgroupMemory*: VkBool32
  dynamicRendering*: VkBool32
  shaderIntegerDotProduct*: VkBool32
  maintenance4*: VkBool32


type VkPhysicalDeviceVulkan13Properties* = object
  sType*: VkStructureType
  pNext*: pointer
  minSubgroupSize*: uint32
  maxSubgroupSize*: uint32
  maxComputeWorkgroupSubgroups*: uint32
  requiredSubgroupSizeStages*: VkShaderStageFlags
  maxInlineUniformBlockSize*: uint32
  maxPerStageDescriptorInlineUniformBlocks*: uint32
  maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks*: uint32
  maxDescriptorSetInlineUniformBlocks*: uint32
  maxDescriptorSetUpdateAfterBindInlineUniformBlocks*: uint32
  maxInlineUniformTotalSize*: uint32
  integerDotProduct8BitUnsignedAccelerated*: VkBool32
  integerDotProduct8BitSignedAccelerated*: VkBool32
  integerDotProduct8BitMixedSignednessAccelerated*: VkBool32
  integerDotProduct4x8BitPackedUnsignedAccelerated*: VkBool32
  integerDotProduct4x8BitPackedSignedAccelerated*: VkBool32
  integerDotProduct4x8BitPackedMixedSignednessAccelerated*: VkBool32
  integerDotProduct16BitUnsignedAccelerated*: VkBool32
  integerDotProduct16BitSignedAccelerated*: VkBool32
  integerDotProduct16BitMixedSignednessAccelerated*: VkBool32
  integerDotProduct32BitUnsignedAccelerated*: VkBool32
  integerDotProduct32BitSignedAccelerated*: VkBool32
  integerDotProduct32BitMixedSignednessAccelerated*: VkBool32
  integerDotProduct64BitUnsignedAccelerated*: VkBool32
  integerDotProduct64BitSignedAccelerated*: VkBool32
  integerDotProduct64BitMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating8BitUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating8BitSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating16BitUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating16BitSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating32BitUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating32BitSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating64BitUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating64BitSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated*: VkBool32
  storageTexelBufferOffsetAlignmentBytes*: VkDeviceSize
  storageTexelBufferOffsetSingleTexelAlignment*: VkBool32
  uniformTexelBufferOffsetAlignmentBytes*: VkDeviceSize
  uniformTexelBufferOffsetSingleTexelAlignment*: VkBool32
  maxBufferSize*: VkDeviceSize


type VkFaultData* = object
  sType*: VkStructureType
  pNext*: pointer
  faultLevel*: VkFaultLevel
  faultType*: VkFaultType


type VkFaultCallbackInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  faultCount*: uint32
  pFaults*: ptr VkFaultData
  pfnFaultCallback*: PFN_vkFaultCallbackFunction


type VkPhysicalDeviceToolProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  name*: array[VK_MAX_EXTENSION_NAME_SIZE, char]
  version*: array[VK_MAX_EXTENSION_NAME_SIZE, char]
  purposes*: VkToolPurposeFlags
  description*: array[VK_MAX_DESCRIPTION_SIZE, char]
  layer*: array[VK_MAX_EXTENSION_NAME_SIZE, char]


type VkPipelineOfflineCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  pipelineIdentifier*: array[VK_UUID_SIZE, uint8]
  matchControl*: VkPipelineMatchControl
  poolEntrySize*: VkDeviceSize


type VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderZeroInitializeWorkgroupMemory*: VkBool32


type VkPhysicalDeviceImageRobustnessFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  robustImageAccess*: VkBool32


type VkBufferCopy2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcOffset*: VkDeviceSize
  dstOffset*: VkDeviceSize
  size*: VkDeviceSize


type VkImageCopy2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcSubresource*: VkImageSubresourceLayers
  srcOffset*: VkOffset3D
  dstSubresource*: VkImageSubresourceLayers
  dstOffset*: VkOffset3D
  extent*: VkExtent3D


type VkImageBlit2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcSubresource*: VkImageSubresourceLayers
  srcOffsets*: array[2, VkOffset3D]
  dstSubresource*: VkImageSubresourceLayers
  dstOffsets*: array[2, VkOffset3D]


type VkBufferImageCopy2* = object
  sType*: VkStructureType
  pNext*: pointer
  bufferOffset*: VkDeviceSize
  bufferRowLength*: uint32
  bufferImageHeight*: uint32
  imageSubresource*: VkImageSubresourceLayers
  imageOffset*: VkOffset3D
  imageExtent*: VkExtent3D


type VkImageResolve2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcSubresource*: VkImageSubresourceLayers
  srcOffset*: VkOffset3D
  dstSubresource*: VkImageSubresourceLayers
  dstOffset*: VkOffset3D
  extent*: VkExtent3D


type VkCopyBufferInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcBuffer*: VkBuffer
  dstBuffer*: VkBuffer
  regionCount*: uint32
  pRegions*: ptr VkBufferCopy2


type VkCopyImageInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcImage*: VkImage
  srcImageLayout*: VkImageLayout
  dstImage*: VkImage
  dstImageLayout*: VkImageLayout
  regionCount*: uint32
  pRegions*: ptr VkImageCopy2


type VkBlitImageInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcImage*: VkImage
  srcImageLayout*: VkImageLayout
  dstImage*: VkImage
  dstImageLayout*: VkImageLayout
  regionCount*: uint32
  pRegions*: ptr VkImageBlit2
  filter*: VkFilter


type VkCopyBufferToImageInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcBuffer*: VkBuffer
  dstImage*: VkImage
  dstImageLayout*: VkImageLayout
  regionCount*: uint32
  pRegions*: ptr VkBufferImageCopy2


type VkCopyImageToBufferInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcImage*: VkImage
  srcImageLayout*: VkImageLayout
  dstBuffer*: VkBuffer
  regionCount*: uint32
  pRegions*: ptr VkBufferImageCopy2


type VkResolveImageInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcImage*: VkImage
  srcImageLayout*: VkImageLayout
  dstImage*: VkImage
  dstImageLayout*: VkImageLayout
  regionCount*: uint32
  pRegions*: ptr VkImageResolve2


type VkPhysicalDeviceShaderTerminateInvocationFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderTerminateInvocation*: VkBool32


type VkMemoryBarrier2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcStageMask*: VkPipelineStageFlags2
  srcAccessMask*: VkAccessFlags2
  dstStageMask*: VkPipelineStageFlags2
  dstAccessMask*: VkAccessFlags2


type VkImageMemoryBarrier2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcStageMask*: VkPipelineStageFlags2
  srcAccessMask*: VkAccessFlags2
  dstStageMask*: VkPipelineStageFlags2
  dstAccessMask*: VkAccessFlags2
  oldLayout*: VkImageLayout
  newLayout*: VkImageLayout
  srcQueueFamilyIndex*: uint32
  dstQueueFamilyIndex*: uint32
  image*: VkImage
  subresourceRange*: VkImageSubresourceRange


type VkBufferMemoryBarrier2* = object
  sType*: VkStructureType
  pNext*: pointer
  srcStageMask*: VkPipelineStageFlags2
  srcAccessMask*: VkAccessFlags2
  dstStageMask*: VkPipelineStageFlags2
  dstAccessMask*: VkAccessFlags2
  srcQueueFamilyIndex*: uint32
  dstQueueFamilyIndex*: uint32
  buffer*: VkBuffer
  offset*: VkDeviceSize
  size*: VkDeviceSize


type VkDependencyInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  dependencyFlags*: VkDependencyFlags
  memoryBarrierCount*: uint32
  pMemoryBarriers*: ptr VkMemoryBarrier2
  bufferMemoryBarrierCount*: uint32
  pBufferMemoryBarriers*: ptr VkBufferMemoryBarrier2
  imageMemoryBarrierCount*: uint32
  pImageMemoryBarriers*: ptr VkImageMemoryBarrier2


type VkSemaphoreSubmitInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  semaphore*: VkSemaphore
  value*: uint64
  stageMask*: VkPipelineStageFlags2
  deviceIndex*: uint32


type VkCommandBufferSubmitInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  commandBuffer*: VkCommandBuffer
  deviceMask*: uint32


type VkSubmitInfo2* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkSubmitFlags
  waitSemaphoreInfoCount*: uint32
  pWaitSemaphoreInfos*: ptr VkSemaphoreSubmitInfo
  commandBufferInfoCount*: uint32
  pCommandBufferInfos*: ptr VkCommandBufferSubmitInfo
  signalSemaphoreInfoCount*: uint32
  pSignalSemaphoreInfos*: ptr VkSemaphoreSubmitInfo


type VkPhysicalDeviceSynchronization2Features* = object
  sType*: VkStructureType
  pNext*: pointer
  synchronization2*: VkBool32


type VkPhysicalDeviceVulkanSC10Properties* = object
  sType*: VkStructureType
  pNext*: pointer
  deviceNoDynamicHostAllocations*: VkBool32
  deviceDestroyFreesMemory*: VkBool32
  commandPoolMultipleCommandBuffersRecording*: VkBool32
  commandPoolResetCommandBuffer*: VkBool32
  commandBufferSimultaneousUse*: VkBool32
  secondaryCommandBufferNullOrImagelessFramebuffer*: VkBool32
  recycleDescriptorSetMemory*: VkBool32
  recyclePipelineMemory*: VkBool32
  maxRenderPassSubpasses*: uint32
  maxRenderPassDependencies*: uint32
  maxSubpassInputAttachments*: uint32
  maxSubpassPreserveAttachments*: uint32
  maxFramebufferAttachments*: uint32
  maxDescriptorSetLayoutBindings*: uint32
  maxQueryFaultCount*: uint32
  maxCallbackFaultCount*: uint32
  maxCommandPoolCommandBuffers*: uint32
  maxCommandBufferSize*: VkDeviceSize


type VkPipelinePoolSize* = object
  sType*: VkStructureType
  pNext*: pointer
  poolEntrySize*: VkDeviceSize
  poolEntryCount*: uint32


type VkDeviceObjectReservationCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  pipelineCacheCreateInfoCount*: uint32
  pPipelineCacheCreateInfos*: ptr VkPipelineCacheCreateInfo
  pipelinePoolSizeCount*: uint32
  pPipelinePoolSizes*: ptr VkPipelinePoolSize
  semaphoreRequestCount*: uint32
  commandBufferRequestCount*: uint32
  fenceRequestCount*: uint32
  deviceMemoryRequestCount*: uint32
  bufferRequestCount*: uint32
  imageRequestCount*: uint32
  eventRequestCount*: uint32
  queryPoolRequestCount*: uint32
  bufferViewRequestCount*: uint32
  imageViewRequestCount*: uint32
  layeredImageViewRequestCount*: uint32
  pipelineCacheRequestCount*: uint32
  pipelineLayoutRequestCount*: uint32
  renderPassRequestCount*: uint32
  graphicsPipelineRequestCount*: uint32
  computePipelineRequestCount*: uint32
  descriptorSetLayoutRequestCount*: uint32
  samplerRequestCount*: uint32
  descriptorPoolRequestCount*: uint32
  descriptorSetRequestCount*: uint32
  framebufferRequestCount*: uint32
  commandPoolRequestCount*: uint32
  samplerYcbcrConversionRequestCount*: uint32
  surfaceRequestCount*: uint32
  swapchainRequestCount*: uint32
  displayModeRequestCount*: uint32
  subpassDescriptionRequestCount*: uint32
  attachmentDescriptionRequestCount*: uint32
  descriptorSetLayoutBindingRequestCount*: uint32
  descriptorSetLayoutBindingLimit*: uint32
  maxImageViewMipLevels*: uint32
  maxImageViewArrayLayers*: uint32
  maxLayeredImageViewMipLevels*: uint32
  maxOcclusionQueriesPerPool*: uint32
  maxPipelineStatisticsQueriesPerPool*: uint32
  maxTimestampQueriesPerPool*: uint32
  maxImmutableSamplersPerDescriptorSetLayout*: uint32


type VkCommandPoolMemoryReservationCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  commandPoolReservedSize*: VkDeviceSize
  commandPoolMaxCommandBuffers*: uint32


type VkCommandPoolMemoryConsumption* = object
  sType*: VkStructureType
  pNext*: pointer
  commandPoolAllocated*: VkDeviceSize
  commandPoolReservedSize*: VkDeviceSize
  commandBufferAllocated*: VkDeviceSize


type VkPhysicalDeviceVulkanSC10Features* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderAtomicInstructions*: VkBool32


type VkPhysicalDeviceShaderIntegerDotProductFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  shaderIntegerDotProduct*: VkBool32


type VkPhysicalDeviceShaderIntegerDotProductProperties* = object
  sType*: VkStructureType
  pNext*: pointer
  integerDotProduct8BitUnsignedAccelerated*: VkBool32
  integerDotProduct8BitSignedAccelerated*: VkBool32
  integerDotProduct8BitMixedSignednessAccelerated*: VkBool32
  integerDotProduct4x8BitPackedUnsignedAccelerated*: VkBool32
  integerDotProduct4x8BitPackedSignedAccelerated*: VkBool32
  integerDotProduct4x8BitPackedMixedSignednessAccelerated*: VkBool32
  integerDotProduct16BitUnsignedAccelerated*: VkBool32
  integerDotProduct16BitSignedAccelerated*: VkBool32
  integerDotProduct16BitMixedSignednessAccelerated*: VkBool32
  integerDotProduct32BitUnsignedAccelerated*: VkBool32
  integerDotProduct32BitSignedAccelerated*: VkBool32
  integerDotProduct32BitMixedSignednessAccelerated*: VkBool32
  integerDotProduct64BitUnsignedAccelerated*: VkBool32
  integerDotProduct64BitSignedAccelerated*: VkBool32
  integerDotProduct64BitMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating8BitUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating8BitSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating16BitUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating16BitSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating32BitUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating32BitSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating64BitUnsignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating64BitSignedAccelerated*: VkBool32
  integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated*: VkBool32


type VkFormatProperties3* = object
  sType*: VkStructureType
  pNext*: pointer
  linearTilingFeatures*: VkFormatFeatureFlags2
  optimalTilingFeatures*: VkFormatFeatureFlags2
  bufferFeatures*: VkFormatFeatureFlags2


type VkPipelineRenderingCreateInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  viewMask*: uint32
  colorAttachmentCount*: uint32
  pColorAttachmentFormats*: ptr VkFormat
  depthAttachmentFormat*: VkFormat
  stencilAttachmentFormat*: VkFormat


type VkRenderingInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkRenderingFlags
  renderArea*: VkRect2D
  layerCount*: uint32
  viewMask*: uint32
  colorAttachmentCount*: uint32
  pColorAttachments*: ptr VkRenderingAttachmentInfo
  pDepthAttachment*: ptr VkRenderingAttachmentInfo
  pStencilAttachment*: ptr VkRenderingAttachmentInfo


type VkRenderingAttachmentInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  imageView*: VkImageView
  imageLayout*: VkImageLayout
  resolveMode*: VkResolveModeFlagBits
  resolveImageView*: VkImageView
  resolveImageLayout*: VkImageLayout
  loadOp*: VkAttachmentLoadOp
  storeOp*: VkAttachmentStoreOp
  clearValue*: VkClearValue


type VkPhysicalDeviceDynamicRenderingFeatures* = object
  sType*: VkStructureType
  pNext*: pointer
  dynamicRendering*: VkBool32


type VkCommandBufferInheritanceRenderingInfo* = object
  sType*: VkStructureType
  pNext*: pointer
  flags*: VkRenderingFlags
  viewMask*: uint32
  colorAttachmentCount*: uint32
  pColorAttachmentFormats*: ptr VkFormat
  depthAttachmentFormat*: VkFormat
  stencilAttachmentFormat*: VkFormat
  rasterizationSamples*: VkSampleCountFlagBits



