# AutoGenerated File
# TODO: Add VulkanNim Header here
import std/sets

## API Constants
const MaxPhysicalDeviceNameSize *:uint32= 256
const UuidSize *:uint32= 16
const LuidSize *:uint32= 8
const MaxExtensionNameSize *:uint32= 256
const MaxDescriptionSize *:uint32= 256
const MaxMemoryTypes *:uint32= 32
const MaxMemoryHeaps *:uint32= 16
const LodClampNone *:float32= 1000.0'f32
const RemainingMipLevels *:uint32= not 0'u32
const RemainingArrayLayers *:uint32= not 0'u32
const Remaining3dSlicesExt *:uint32= not 0'u32
const WholeSize *:uint64= not 0'u64
const AttachmentUnused *:uint32= not 0'u32
const True *:uint32= 1
const False *:uint32= 0
const QueueFamilyIgnored *:uint32= not 0'u32
const QueueFamilyExternal *:uint32= not 1'u32
const QueueFamilyForeignExt *:uint32= not 2'u32
const SubpassExternal *:uint32= not 0'u32
const MaxDeviceGroupSize *:uint32= 32
const MaxDriverNameSize *:uint32= 256
const MaxDriverInfoSize *:uint32= 256
const ShaderUnusedKhr *:uint32= not 0'u32
const MaxGlobalPrioritySizeKhr *:uint32= 16
const MaxShaderModuleIdentifierSizeExt *:uint32= 32
const ShaderIndexUnusedAmdx *:uint32= not 0'u32

## API Constant Aliases
const LuidSizeKhr *:uint32= LuidSize
const QueueFamilyExternalKhr *:uint32= QueueFamilyExternal
const MaxDeviceGroupSizeKhr *:uint32= MaxDeviceGroupSize
const MaxDriverNameSizeKhr *:uint32= MaxDriverNameSize
const MaxDriverInfoSizeKhr *:uint32= MaxDriverInfoSize
const ShaderUnusedNv *:uint32= ShaderUnusedKhr
const MaxGlobalPrioritySizeExt *:uint32= MaxGlobalPrioritySizeKhr


