import ../parser/base; export base

const VulkanNimHeader * = """
{.experimental: "codeReordering".}
# AutoGenerated File
# TODO: Add VulkanNim Header here"""

type Generator * = object
  api      *:string  ## needs to be of value "vulkan" or "vulkansc"
  registry *:Registry
  #C_like *: bool


#_______________________________________
# Generator Tools used by all modules
#___________________
func getDeprecated *(data :AliasData; name :string) :string=
  ## Returns a {.deprecated: reason.} pragma string, based on the information contained in the given AliasData
  if data.deprecated == "": return ""
  var reason :string= case data.deprecated:
  of "aliased":  &"{data.deprecated}:  {name}  has been aliased to  {data.name}"
  else: raise newException(CodegenError, &"Tried to add codegen for a deprecated alias, but it contains an unknown reason:\n └─> {data.deprecated}\n")
  result = &" {{.deprecated: \"{reason}\".}}"

