# std dependencies
import std/xmltree


type Generator * = object
  doc *:XmlNode
  api *:string ## needs to be of value "vulkan" or "vulkansc"

const LicensePlate * = """
# AutoGenerated File
# TODO: Add License here"""

