# std dependencies
import std/strutils
import std/strformat
# Generator dependencies
import ../helpers


const VulkanNimHeader * = """
# AutoGenerated File
# TODO: Add VulkanNim Header here"""


const MITtemplate = """
{VulkanNimHeader}

#[ MIT License | {copyr}

{MIT} ]#"""

const MIT = """
Permission is hereby granted, free of charge, to any person obtaining a copy of this software
and associated documentation files (the “Software”), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."""

proc getMIT *(text :string) :string=
  ## Generates an MIT message for the library
  var copyr :string 
  for line in text.splitLines():
    if   "Copyright" in line:  copyr = line
    elif "SPDX-License-Identifier" in line and "MIT" notin line:
      unreachable &"Tried to get MIT license text from an xml spec file that does not list support for MIT. Text contains:\n{text}\nLine contains:\n{line}"
  result = fmt( MITtemplate )

